// Giữ nguyên id sau khi phát hành để không mất thành tựu đã mở khóa.
export const achievementGroups = [
  {
    id: "milestones",
    title: "🌱 Cột mốc",
    sections: [
      "Học tập và trưởng thành",
      "Dấu mốc tuổi đời",
      "Tình yêu và gia đình",
    ],
  },
  {
    id: "assets",
    title: "💰 Tài sản",
    sections: ["Tiền bạc", "Bất động sản và kinh doanh", "Phương tiện"],
  },
  {
    id: "careers",
    title: "💼 Công việc",
    sections: [
      "Nghệ thuật",
      "Chuyên môn và lãnh đạo",
      "Thể thao và thể thao điện tử",
      "Sáng tạo nội dung",
    ],
  },
  {
    id: "other",
    title: "🔮 Khác",
    sections: [
      "May mắn và biến cố",
      "Những câu chuyện bí ẩn",
      "Chỉ số nhân vật",
    ],
  },
];

const flag = (age) => ({ kind: "flag", ...(age === undefined ? {} : { age }) });
const number = (field, value, strict = false) => ({
  kind: "number",
  field,
  value,
  strict,
});
const item = (id, group, section, icon, title, description, rule) => ({
  id,
  group,
  section,
  icon,
  title,
  description,
  rule,
});

export const achievements = [
  item(
    "primary-school",
    "milestones",
    "Học tập và trưởng thành",
    "🎒",
    "Ngày đầu đến trường",
    "Bắt đầu hành trình học tập tại trường tiểu học.",
    flag(),
  ),
  item(
    "secondary-school",
    "milestones",
    "Học tập và trưởng thành",
    "📚",
    "Lên cấp 2",
    "Trở thành học sinh trung học cơ sở.",
    flag(),
  ),
  item(
    "high-school",
    "milestones",
    "Học tập và trưởng thành",
    "🏫",
    "Lên cấp 3",
    "Bước vào những năm học trung học phổ thông.",
    flag(),
  ),
  item(
    "university-18",
    "milestones",
    "Học tập và trưởng thành",
    "🎓",
    "Tân sinh viên",
    "Thi đỗ đại học khi vừa tròn 18 tuổi.",
    flag(18),
  ),
  item(
    "voluntary-enlistment",
    "milestones",
    "Học tập và trưởng thành",
    "🪖",
    "Bảo vệ Tổ quốc",
    "Chủ động chọn con đường nhập ngũ để phục vụ Tổ quốc.",
    flag(),
  ),
  item(
    "age-30",
    "milestones",
    "Dấu mốc tuổi đời",
    "🌳",
    "Ba mươi năm cuộc đời",
    "Đón sinh nhật lần thứ 30.",
    number("age", 30),
  ),
  item(
    "age-60",
    "milestones",
    "Dấu mốc tuổi đời",
    "🌅",
    "Sáu mươi mùa xuân",
    "Đi qua 60 mùa xuân của cuộc đời.",
    number("age", 60),
  ),
  item(
    "age-90",
    "milestones",
    "Dấu mốc tuổi đời",
    "🧧",
    "Chín mươi nồi bánh chưng",
    "Sống đến tuổi 90 và tiếp tục viết câu chuyện của mình.",
    number("age", 90),
  ),
  item(
    "age-over-100",
    "milestones",
    "Dấu mốc tuổi đời",
    "🐢",
    "Sống dai thành huyền thoại",
    "Vượt qua tuổi 100 để trở thành một huyền thoại sống.",
    number("age", 100, true),
  ),
  item(
    "first-love",
    "milestones",
    "Tình yêu và gia đình",
    "💕",
    "Thoát ế",
    "Bắt đầu một mối quan hệ yêu đương.",
    flag(),
  ),
  item(
    "married",
    "milestones",
    "Tình yêu và gia đình",
    "💍",
    "Gia đình nhỏ",
    "Kết hôn và xây dựng tổ ấm của riêng mình.",
    flag(),
  ),
  item(
    "first-child",
    "milestones",
    "Tình yêu và gia đình",
    "👶",
    "Đứa con đầu lòng",
    "Chào đón người con đầu tiên.",
    flag(),
  ),

  item(
    "money-1m",
    "assets",
    "Tiền bạc",
    "🐷",
    "Triệu đồng đầu tiên",
    "Tích lũy ít nhất 1.000.000 VNĐ trong ví.",
    number("money", 1000000),
  ),
  item(
    "money-10m",
    "assets",
    "Tiền bạc",
    "💵",
    "Mười triệu trong tay",
    "Nâng số tiền trong ví lên ít nhất 10.000.000 VNĐ.",
    number("money", 10000000),
  ),
  item(
    "millionaire",
    "assets",
    "Tiền bạc",
    "💸",
    "Triệu phú",
    "Sở hữu số tiền vượt mốc 1.000.000 VNĐ.",
    number("money", 1000000, true),
  ),
  item(
    "billionaire",
    "assets",
    "Tiền bạc",
    "💎",
    "Tỷ phú",
    "Sở hữu số tiền vượt mốc 1.000.000.000 VNĐ.",
    number("money", 1000000000, true),
  ),
  item(
    "own-house",
    "assets",
    "Bất động sản và kinh doanh",
    "🏠",
    "Nhà cao cửa rộng",
    "Sở hữu một căn nhà lầu.",
    flag(),
  ),
  item(
    "own-resort",
    "assets",
    "Bất động sản và kinh doanh",
    "🏝️",
    "Chủ khu nghỉ dưỡng",
    "Đưa một resort vào danh sách tài sản của bạn.",
    flag(),
  ),
  item(
    "own-hotel",
    "assets",
    "Bất động sản và kinh doanh",
    "🏨",
    "Ông chủ khách sạn",
    "Sở hữu một khách sạn.",
    flag(),
  ),
  item(
    "own-noodle-cart",
    "assets",
    "Bất động sản và kinh doanh",
    "🍜",
    "Gánh hủ tiếu đầu đời",
    "Bắt đầu kinh doanh với một xe hủ tiếu.",
    flag(),
  ),
  item(
    "own-restaurant",
    "assets",
    "Bất động sản và kinh doanh",
    "🍽️",
    "Chủ nhà hàng",
    "Sở hữu một nhà hàng của riêng mình.",
    flag(),
  ),
  item(
    "own-cafe",
    "assets",
    "Bất động sản và kinh doanh",
    "☕",
    "Góc cà phê của tôi",
    "Trở thành chủ một quán cà phê.",
    flag(),
  ),
  item(
    "own-motorbike",
    "assets",
    "Phương tiện",
    "🛵",
    "Hai bánh tự do",
    "Sở hữu chiếc xe máy đầu tiên.",
    flag(),
  ),
  item(
    "own-big-bike",
    "assets",
    "Phương tiện",
    "🏍️",
    "Đam mê tốc độ",
    "Sở hữu chiếc mô tô phân khối lớn đầu tiên.",
    flag(),
  ),
  item(
    "own-car",
    "assets",
    "Phương tiện",
    "🚗",
    "Bốn bánh đầu đời",
    "Sở hữu chiếc ô tô đầu tiên.",
    flag(),
  ),
  item(
    "own-lamborghini",
    "assets",
    "Phương tiện",
    "🐂",
    "Giấc mơ Lamborghini",
    "Bổ sung một chiếc Lamborghini vào bộ sưu tập xe.",
    flag(),
  ),
  item(
    "own-porsche",
    "assets",
    "Phương tiện",
    "🏎️",
    "Dấu ấn Porsche",
    "Trở thành chủ nhân của một chiếc Porsche.",
    flag(),
  ),
  item(
    "own-rolls-royce",
    "assets",
    "Phương tiện",
    "🚘",
    "Đẳng cấp Rolls-Royce",
    "Sở hữu một chiếc Rolls-Royce.",
    flag(),
  ),
  item(
    "own-private-jet",
    "assets",
    "Phương tiện",
    "✈️",
    "Bầu trời riêng",
    "Sở hữu máy bay riêng của bạn.",
    flag(),
  ),

  item(
    "career-actor",
    "careers",
    "Nghệ thuật",
    "🎬",
    "Diễn viên chuyên nghiệp",
    "Theo đuổi điện ảnh và thăng tiến đến bậc diễn viên chuyên nghiệp.",
    flag(),
  ),
  item(
    "career-singer",
    "careers",
    "Nghệ thuật",
    "🎤",
    "Ca sĩ chuyên nghiệp",
    "Phát triển sự nghiệp ca hát đến bậc ca sĩ chuyên nghiệp.",
    flag(),
  ),
  item(
    "career-painter",
    "careers",
    "Nghệ thuật",
    "🎨",
    "Họa sĩ chuyên nghiệp",
    "Theo đuổi mỹ thuật và đạt bậc họa sĩ chuyên nghiệp.",
    flag(),
  ),
  item(
    "career-military",
    "careers",
    "Chuyên môn và lãnh đạo",
    "🪖",
    "Chuyên gia quân sự",
    "Phát triển sự nghiệp quân ngũ đến bậc chuyên gia quân sự.",
    flag(),
  ),
  item(
    "career-doctor",
    "careers",
    "Chuyên môn và lãnh đạo",
    "🩺",
    "Trưởng khoa",
    "Theo ngành Y và được bổ nhiệm làm trưởng khoa.",
    flag(),
  ),
  item(
    "career-programmer",
    "careers",
    "Chuyên môn và lãnh đạo",
    "💻",
    "Chuyên gia lập trình",
    "Thăng tiến trong ngành IT đến bậc chuyên gia lập trình.",
    flag(),
  ),
  item(
    "career-accountant",
    "careers",
    "Chuyên môn và lãnh đạo",
    "🧾",
    "Chuyên gia kế toán",
    "Xây dựng sự nghiệp kế toán đến bậc chuyên gia.",
    flag(),
  ),
  item(
    "career-law",
    "careers",
    "Chuyên môn và lãnh đạo",
    "⚖️",
    "Chuyên gia pháp lý",
    "Theo đuổi ngành luật và đạt bậc chuyên gia pháp lý.",
    flag(),
  ),
  item(
    "career-principal",
    "careers",
    "Chuyên môn và lãnh đạo",
    "🏫",
    "Hiệu trưởng",
    "Phát triển sự nghiệp giáo dục và trở thành hiệu trưởng.",
    flag(),
  ),
  item(
    "career-psychologist",
    "careers",
    "Chuyên môn và lãnh đạo",
    "🧠",
    "Chuyên gia tâm lý",
    "Theo ngành tâm lý học và đạt bậc chuyên gia tâm lý.",
    flag(),
  ),
  item(
    "career-football",
    "careers",
    "Thể thao và thể thao điện tử",
    "⚽",
    "Cầu thủ chuyên nghiệp",
    "Phát triển sự nghiệp bóng đá đến cấp độ chuyên nghiệp.",
    flag(),
  ),
  item(
    "career-athlete",
    "careers",
    "Thể thao và thể thao điện tử",
    "🏅",
    "Vận động viên chuyên nghiệp",
    "Đạt cấp độ chuyên nghiệp ở một môn thể thao ngoài bóng đá.",
    flag(),
  ),
  item(
    "career-gamer",
    "careers",
    "Thể thao và thể thao điện tử",
    "🎮",
    "Game thủ chuyên nghiệp",
    "Theo đuổi thi đấu game và trở thành tuyển thủ chuyên nghiệp.",
    flag(),
  ),
  item(
    "career-tiktok",
    "careers",
    "Sáng tạo nội dung",
    "📱",
    "TikToker chuyên nghiệp",
    "Phát triển sự nghiệp TikTok đến bậc nhà sáng tạo chuyên nghiệp.",
    flag(),
  ),
  item(
    "tiktok-10m",
    "careers",
    "Sáng tạo nội dung",
    "🌟",
    "Mười triệu người theo dõi",
    "Đạt ít nhất 10.000.000 người theo dõi trên TikTok.",
    number("tiktokFollowers", 10000000),
  ),
  item(
    "career-youtube",
    "careers",
    "Sáng tạo nội dung",
    "🎥",
    "YouTuber chuyên nghiệp",
    "Phát triển sự nghiệp YouTube đến bậc nhà sáng tạo chuyên nghiệp.",
    flag(),
  ),
  item(
    "youtube-10m",
    "careers",
    "Sáng tạo nội dung",
    "▶️",
    "Mười triệu người đăng ký",
    "Đạt ít nhất 10.000.000 người đăng ký trên YouTube.",
    number("youtubeSubscribers", 10000000),
  ),

  item(
    "first-lottery-win",
    "other",
    "May mắn và biến cố",
    "🎟️",
    "Lần đầu trúng số",
    "Nhận giải thưởng xổ số đầu tiên.",
    flag(),
  ),
  item(
    "gambling-loss-10m",
    "other",
    "May mắn và biến cố",
    "🎲",
    "Cờ bạc là bác thằng bần",
    "Để tổng tiền thua cờ bạc trong một cuộc đời chạm mốc 10.000.000 VNĐ.",
    number("gamblingLosses", 10000000),
  ),
  item(
    "story-diamond",
    "other",
    "Những câu chuyện bí ẩn",
    "💎",
    "Tìm thấy mỏ kim cương",
    "Nắm bắt cơ hội thám hiểm ở tuổi 20 và đi đến kết cục tìm thấy mỏ kim cương.",
    flag(),
  ),
  item(
    "story-alien",
    "other",
    "Những câu chuyện bí ẩn",
    "👽",
    "Thực thể ngoài vũ trụ",
    "Khám phá đến cùng cuộc gặp gỡ kỳ lạ có thể xuất hiện ở tuổi 30.",
    flag(),
  ),
  item(
    "story-reincarnation",
    "other",
    "Những câu chuyện bí ẩn",
    "👻",
    "Oan hồn đầu thai",
    "Theo dấu câu chuyện tâm linh ở tuổi 40 và giúp oan hồn được đầu thai.",
    flag(),
  ),
  item(
    "story-hero",
    "other",
    "Những câu chuyện bí ẩn",
    "🦸",
    "Vinh danh người hùng",
    "Đưa ra những lựa chọn anh hùng trong biến cố có thể xuất hiện ở tuổi 50.",
    flag(),
  ),
  item(
    "story-reward",
    "other",
    "Những câu chuyện bí ẩn",
    "🎁",
    "Phần thưởng xứng đáng",
    "Hoàn thành hành trình đặc biệt có thể xuất hiện ở tuổi 60 để nhận phần thưởng xứng đáng.",
    flag(),
  ),
  item(
    "story-fraud",
    "other",
    "Những câu chuyện bí ẩn",
    "🕵️",
    "Triệt phá lừa đảo",
    "Lần theo những manh mối ở tuổi 70 và đưa đường dây lừa đảo ra ánh sáng.",
    flag(),
  ),
  item(
    "story-lucky",
    "other",
    "Những câu chuyện bí ẩn",
    "🍀",
    "Thần may mắn",
    "Nắm bắt cơ hội hiếm có ở tuổi 80 và đi đến kết cục may mắn nhất.",
    flag(),
  ),
  item(
    "story-final-happiness",
    "other",
    "Những câu chuyện bí ẩn",
    "🌅",
    "Hạnh phúc cuối đời",
    "Tìm đến kết thúc viên mãn trong câu chuyện đặc biệt có thể xuất hiện ở tuổi 90.",
    flag(),
  ),
  item(
    "health-100",
    "other",
    "Chỉ số nhân vật",
    "💪",
    "Tràn đầy sức sống",
    "Đưa sức khỏe lên mức 100%.",
    number("health", 100),
  ),
  item(
    "intelligence-100",
    "other",
    "Chỉ số nhân vật",
    "🧠",
    "Trí tuệ xuất chúng",
    "Đưa trí tuệ lên mức 100%.",
    number("intelligence", 100),
  ),
  item(
    "happiness-100",
    "other",
    "Chỉ số nhân vật",
    "❤️",
    "Hạnh phúc trọn vẹn",
    "Đưa hạnh phúc lên mức 100%.",
    number("happiness", 100),
  ),
  item(
    "appearance-100",
    "other",
    "Chỉ số nhân vật",
    "✨",
    "Ngoại hình nổi bật",
    "Đưa ngoại hình lên mức 100%.",
    number("appearance", 100),
  ),
];

export function meetsAchievement(achievement, player = {}) {
  const rule = achievement.rule;
  if (rule.kind === "flag") {
    return player.achievementFlags?.[achievement.id] === true;
  }
  const value = player[rule.field];
  return (
    Number.isFinite(value) &&
    (rule.strict ? value > rule.value : value >= rule.value)
  );
}

// Chỉ gọi khi hành động đã thành công, sau khi tuổi mới được áp dụng.
// Hàm này ghi nhận kết quả, không tự kiểm tra/áp dụng việc mua tài sản hay thăng chức.
export function recordAchievementFlags(state, ids = []) {
  if (!state?.player || !Array.isArray(ids)) return;
  const oldFlags = state.player.achievementFlags;
  if (!oldFlags || typeof oldFlags !== "object" || Array.isArray(oldFlags)) {
    state.player.achievementFlags = {};
  }
  for (const id of ids) {
    const achievement = achievements.find((entry) => entry.id === id);
    if (!achievement || achievement.rule.kind !== "flag") continue;
    if (
      achievement.rule.age !== undefined &&
      state.player.age !== achievement.rule.age
    )
      continue;
    state.player.achievementFlags[id] = true;
  }
}
