import { ensureEventOpenMoji } from "./event-openmoji.js";

const art = (code, alt) => {
  const image = new URL(`./img/events/openmoji/color/svg/${code}.svg`, import.meta.url).href;
  return { image, imageAlt: alt, imageFallback: image, imageFallbackAlt: alt };
};

// Tuổi 29 bổ sung vào hai sự kiện đã có. Tuổi 30 và 35 dành một
// chỗ cho sự kiện đặc biệt sau này; các tuổi còn lại có ba sự kiện thường.
const stories = {
  29: [
    ["lich-hen", "1F4C5", "Lịch hẹn kín cả tuần",
      "Tôi nhìn lịch: việc cần làm, cuộc hẹn bạn bè và một buổi tối định nghỉ ngơi đều chen vào nhau. Có vẻ người cần đặt lịch gặp tôi nhất lại là… chính tôi!",
      ["Sắp xếp lại, chừa giờ nghỉ", "Một tuần vừa sức", "Tôi cân nhắc điều quan trọng, đổi một cuộc hẹn và dành thời gian nghỉ ngơi. Lịch bớt kín, đầu óc cũng nhẹ hơn.", { intelligence: 2, health: 2 }, "1F4C5"],
      ["Hẹn bạn đi bộ chung", "Vừa gặp bạn vừa vận động", "Tôi rủ bạn đi bộ thay vì ngồi quán. Chúng tôi trò chuyện vui vẻ và trở về với đôi chân hơi mỏi nhưng tinh thần thoải mái.", { health: 3, happiness: 2 }, "1F6B6"]],
  ],
  30: [
    ["sinh-nhat", "1F389", "Ba mươi, một bữa cơm đáng nhớ",
      "Sinh nhật ba mươi đến. Bạn bè hỏi tôi muốn quà gì; tôi chợt thấy một bữa cơm có đủ người thương quý cũng đã là món quà lớn.",
      ["Mời vài người thân thiết", "Bữa cơm tuổi ba mươi", "Tôi chuẩn bị một bữa cơm giản dị. Mọi người kể chuyện, cười vui và chúc nhau một năm bình an.", { happiness: 4 }, "1F373"],
      ["Dành ngày riêng cho mình", "Lời hẹn với bản thân", "Tôi đi dạo, viết vài điều mình biết ơn và chọn một việc muốn thử trong tuổi ba mươi. Không cần có mọi đáp án ngay hôm nay.", { intelligence: 2, happiness: 2 }, "1F4D6"]],
    ["du-phong", "1F4B0", "Chiếc quạt chọn đúng lúc để hỏng",
      "Một món đồ dùng trong nhà hỏng đúng tuần nhiều khoản cần thanh toán. Tôi mở sổ chi tiêu và nhận ra khoản dự phòng lâu nay vẫn nằm trong mục ‘để mai tính’.",
      ["Rà lại chi tiêu và lên kế hoạch", "Chủ động trước việc bất ngờ", "Tôi lập kế hoạch cho những khoản cần thiết, đặt một mục tiêu dự phòng vừa sức và xử lý món đồ hỏng theo ngân sách.", { intelligence: 3 }, "1F9EE"],
      ["Hỏi người quen cách sửa", "Một buổi cùng tìm cách", "Tôi hỏi người quen xem có thể sửa món đồ an toàn không. Chúng tôi tìm được phương án phù hợp và tôi học thêm cách chăm đồ dùng.", { intelligence: 2, happiness: 1 }, "1F91D"]],
  ],
  31: [
    ["hang-xom", "1F91D", "Người hàng xóm mới",
      "Hàng xóm mới chuyển đến, loay hoay với mấy thùng đồ trước cửa. Tôi đang xách túi rau, trông cũng chẳng khác đội chuyển nhà là mấy.",
      ["Chào hỏi và giúp một tay", "Láng giềng dễ mến", "Tôi giúp mang một thùng nhỏ và chỉ chỗ mua đồ gần nhà. Một lời chào biến thành cuộc trò chuyện thân thiện.", { happiness: 3 }, "1F91D"],
      ["Chào rồi hẹn lúc rảnh", "Một lời chào đúng lúc", "Tôi chào hàng xóm và nói mình sẽ ghé hỏi thăm khi rảnh. Tôi vẫn giữ được lịch riêng mà không bỏ qua cơ hội làm quen.", { happiness: 1, intelligence: 1 }, "1F4C5"]],
    ["anh-cu", "1F4F8", "Album toàn những tấm ảnh mờ",
      "Tôi mở ảnh cũ, thấy rất nhiều tấm rung tay nhưng chẳng muốn xóa. Có những ngày không đẹp trong ảnh mà lại rất đẹp trong ký ức.",
      ["Sắp xếp và sao lưu ảnh", "Kỷ niệm được giữ gọn", "Tôi chọn ảnh ý nghĩa, ghi vài chú thích và tạo bản sao lưu. Tìm lại một kỷ niệm giờ không cần kéo màn hình cả buổi.", { intelligence: 2, happiness: 2 }, "1F4F8"],
      ["Gửi ảnh cho bạn cũ", "Một tấm ảnh nối câu chuyện", "Tấm ảnh mở đầu cho một cuộc gọi hỏi thăm. Chúng tôi kể chuyện hôm nay rồi bật cười vì kiểu tóc ngày trước.", { happiness: 4 }, "1F4F1"]],
    ["cuoi-tuan", "1F331", "Cuối tuần không cần đi xa",
      "Tôi có một ngày trống mà chưa biết làm gì. Lướt xem chỗ đi chơi một lúc, tôi nhận ra công viên gần nhà cũng lâu rồi chưa ghé.",
      ["Đi dạo công viên", "Một khoảng xanh dễ chịu", "Tôi đi bộ vừa sức, ngắm cây và ngồi nghỉ một lát. Một ngày bình thường cũng có thể làm mình thư giãn.", { health: 3, happiness: 2 }, "1F6B6"],
      ["Chăm lại góc nhà", "Góc nhà thêm sức sống", "Tôi lau cửa sổ, tưới cây và sắp xếp góc đọc sách. Căn nhà quen thuộc bỗng có cảm giác mới.", { happiness: 2, intelligence: 1 }, "1F331"]],
  ],
  32: [
    ["gio-nghi", "1F4C5", "Buổi tối bị thông báo chiếm chỗ",
      "Tôi định nghỉ nhưng điện thoại cứ sáng lên vì những việc chưa thật sự gấp. Bữa tối nguội dần, còn màn hình thì rất chăm chỉ.",
      ["Phân biệt việc gấp và việc để mai", "Giữ lại giờ nghỉ", "Tôi xử lý việc cần thiết rồi đặt giờ trả lời những tin còn lại. Buổi tối có chỗ cho nghỉ ngơi mà việc quan trọng vẫn được theo dõi.", { intelligence: 3, health: 1 }, "1F4C5"],
      ["Cất máy trong lúc ăn", "Bữa tối trọn vẹn hơn", "Tôi dành riêng thời gian ăn uống rồi mới xem lại tin nhắn. Một bữa ăn không vội khiến tôi thấy nhẹ nhõm.", { happiness: 3 }, "1F37D"]],
    ["mon-quen", "1F373", "Nấu món ăn gợi nhớ nhà",
      "Tôi nhớ một món ăn quen mà công thức trong đầu chỉ có ‘nêm vừa miệng’. Hóa ra ký ức nhớ hương vị rất giỏi, nhớ số thìa thì không.",
      ["Gọi hỏi công thức", "Công thức kèm lời hỏi thăm", "Tôi gọi người thân, vừa hỏi cách nấu vừa kể chuyện gần đây. Món ăn thành công và cuộc trò chuyện còn ấm hơn nồi cơm.", { intelligence: 2, happiness: 3 }, "1F373"],
      ["Thử nấu phiên bản của mình", "Một món quen theo cách mới", "Tôi thử từng bước và ghi lại cách nêm hợp khẩu vị. Không giống hoàn toàn ngày xưa nhưng vẫn là một bữa ăn đáng nhớ.", { intelligence: 3 }, "1F4D6"]],
    ["bo-mon", "1F45F", "Bạn rủ thử môn mới",
      "Một người bạn rủ tôi tham gia buổi vận động cho người mới. Tôi nhìn đôi giày rồi tự nhắc: hôm nay tới học, không phải thi vô địch.",
      ["Đi thử với nhịp vừa sức", "Buổi tập có tiếng cười", "Tôi làm quen từng động tác, nghỉ khi cần và vui vì đã thử một điều mới.", { health: 3, happiness: 2 }, "1F45F"],
      ["Chọn đi bộ cùng bạn", "Một cuộc hẹn nhẹ nhàng", "Tôi chọn hoạt động phù hợp hơn với mình. Chúng tôi đi bộ, trò chuyện và vẫn có một buổi gặp vui.", { health: 2, happiness: 2 }, "1F6B6"]],
  ],
  33: [
    ["hoc-moi", "1F4D6", "Trở lại làm người mới",
      "Tôi đăng ký một buổi học ngoài lĩnh vực quen thuộc. Câu đầu tiên của thầy là ‘rất đơn giản’, còn cuốn vở của tôi thì đã đầy dấu hỏi.",
      ["Hỏi và luyện từng bước", "Một bài học rõ dần", "Tôi hỏi điều chưa hiểu và luyện lại từ cơ bản. Suy nghĩ kỹ hơn giúp tôi thấy mình vẫn có thể học điều mới.", { intelligence: 4 }, "1F4D6"],
      ["Rủ bạn học cùng", "Có bạn cùng làm bài", "Chúng tôi giúp nhau hiểu bài và đặt lịch luyện vừa sức. Việc học bớt ngại khi có người cùng bắt đầu.", { intelligence: 2, happiness: 2 }, "1F91D"]],
    ["hoi-tham", "1F4F1", "Cuộc gọi cứ hẹn để mai",
      "Tôi nhìn tin nhắn hỏi thăm từ người thân rồi nhớ ra mình đã hẹn gọi lại mấy hôm. Những ngày bận rộn rất dễ làm một lời hẹn nhỏ kéo dài.",
      ["Gọi hỏi thăm ngay", "Một cuộc gọi được chờ đợi", "Tôi dành thời gian nghe chuyện của người thân và kể về mình. Chẳng có tin gì lớn, chỉ có cảm giác gần nhau hơn.", { happiness: 4 }, "1F4F1"],
      ["Hẹn một buổi gặp cụ thể", "Lời hẹn có ngày giờ", "Tôi thống nhất một thời gian phù hợp với mọi người và ghi vào lịch. Lần này câu ‘hôm nào gặp’ đã có ngày rõ ràng.", { happiness: 2, intelligence: 1 }, "1F4C5"]],
    ["sach", "1F4DA", "Cuốn sách mua lâu chưa mở",
      "Một cuốn sách trên kệ vẫn còn tờ đánh dấu ở trang đầu. Tôi từng mua với quyết tâm rất cao; hình như quyết tâm được cất chung trong túi giấy.",
      ["Đọc vài trang mỗi ngày", "Thói quen từ trang nhỏ", "Tôi đặt một mục tiêu đọc vừa sức và ghi lại điều thú vị. Cuốn sách dần có thêm những trang gấp góc.", { intelligence: 3 }, "1F4D6"],
      ["Đổi sách với bạn", "Cuốn sách tìm người đọc", "Tôi trao đổi sách với một người bạn. Chúng tôi có thêm đề tài trò chuyện và mỗi người tìm được thứ muốn đọc.", { intelligence: 1, happiness: 3 }, "1F91D"]],
  ],
  34: [
    ["ngay-nghi", "1F6CC", "Một ngày nghỉ thật sự",
      "Tôi có ngày nghỉ nhưng danh sách việc vặt vẫn dài. Nhìn đồng hồ, tôi tự hỏi mình đang nghỉ hay chỉ đổi chỗ làm việc.",
      ["Chọn việc cần rồi nghỉ", "Ngày nghỉ có khoảng trống", "Tôi hoàn thành việc cần nhất và để những việc còn lại sang hôm khác. Một khoảng nghỉ giúp tôi lấy lại sức.", { health: 3, happiness: 2 }, "1F6CC"],
      ["Rủ bạn đi dạo", "Bước ra khỏi danh sách việc", "Tôi dành một buổi đi dạo và trò chuyện. Việc nhà vẫn còn đó nhưng tôi trở về với tinh thần dễ chịu hơn.", { health: 2, happiness: 3 }, "1F6B6"]],
    ["goc-anh", "1F4F8", "Bức ảnh cả nhà khó đủ người",
      "Mọi người muốn chụp chung một bức ảnh nhưng lịch ai cũng khác. Tôi nhận ra để đủ mặt đôi khi cần kiên nhẫn hơn chỉnh máy ảnh.",
      ["Thống nhất một ngày gặp", "Bức ảnh có đủ nụ cười", "Tôi cùng mọi người chọn thời gian phù hợp. Buổi gặp có một bức ảnh đẹp và nhiều chuyện để kể.", { happiness: 4, intelligence: 1 }, "1F4F8"],
      ["Ghép kỷ niệm từ ảnh riêng", "Album mỗi người một góc", "Tôi xin ảnh mới của từng người và làm một album chung. Khoảng cách vẫn còn nhưng kỷ niệm được đặt cạnh nhau.", { happiness: 3 }, "1F4D6"]],
    ["so-thich", "1F9E9", "Sở thích nằm ngoài danh sách thành tích",
      "Tôi muốn thử một việc chỉ vì thấy thích, nhưng lại quen hỏi nó có giúp ích gì không. Có lẽ một buổi vui cũng đã là một ích lợi.",
      ["Dành một buổi thử cho vui", "Niềm vui không cần giải thưởng", "Tôi thử sở thích mới và cười vì vài lần vụng về. Không cần thành thạo ngay, tôi vẫn thấy buổi tối đáng nhớ.", { happiness: 4 }, "1F9E9"],
      ["Tìm người cùng sở thích", "Một nhóm bạn mới", "Tôi tham gia một nhóm sinh hoạt nhỏ và làm quen qua những câu chuyện chung. Mỗi người đều từng có buổi đầu bỡ ngỡ.", { happiness: 3, intelligence: 1 }, "1F91D"]],
  ],
  35: [
    ["nhin-lai", "1F4D6", "Nửa chặng đường ba mươi",
      "Ở tuổi ba mươi lăm, tôi đọc lại những mục tiêu cũ. Có điều đã làm được, có điều không còn phù hợp, và có cả ước mơ mình đã quên mất.",
      ["Viết lại điều thật sự muốn", "Mục tiêu hợp với hôm nay", "Tôi nhìn lại điều quan trọng với mình và chọn một mục tiêu vừa sức. Tương lai không cần giống bản kế hoạch viết nhiều năm trước.", { intelligence: 3, happiness: 2 }, "1F4D6"],
      ["Ăn mừng những điều đã làm", "Ghi nhận chặng đường đã qua", "Tôi tự thưởng một buổi gặp bạn và kể về những bước tiến nhỏ. Có những thành công không được ghi trên bằng khen.", { happiness: 4 }, "1F389"]],
    ["giac-ngu", "1F6CC", "Thói quen thức khuya lâu năm",
      "Tôi định ngủ sớm, nhưng một tập phim kéo theo tập tiếp theo. Sáng hôm sau, chuông báo thức vang lên như một lời nhắc rất thẳng thắn.",
      ["Đặt giờ tắt màn hình", "Buổi sáng tỉnh táo hơn", "Tôi điều chỉnh giờ sinh hoạt và dành đủ thời gian nghỉ. Vài tối đầu hơi khó quen nhưng buổi sáng đã dễ chịu hơn.", { health: 4 }, "1F6CC"],
      ["Để phim cho cuối tuần", "Vẫn xem phim, bớt thức khuya", "Tôi dành một khung giờ xem phù hợp hơn. Thói quen giải trí vẫn còn mà giấc ngủ không phải nhường chỗ mãi.", { health: 2, intelligence: 2 }, "1F4C5"]],
  ],
  36: [
    ["sua-do", "1F9F9", "Góc nhà cần chăm lại",
      "Một chiếc ngăn kéo kẹt và vài món đồ thất lạc khiến tôi mất thời gian tìm đồ mỗi sáng. Căn nhà đang âm thầm xin một buổi được chăm sóc.",
      ["Sắp xếp và sửa việc nhỏ", "Buổi sáng bớt loay hoay", "Tôi dọn gọn, xử lý việc đơn giản và nhờ người có chuyên môn với phần khó. Đồ dùng trở lại đúng chỗ.", { intelligence: 2, happiness: 2 }, "1F9F9"],
      ["Chia việc thành từng buổi", "Chăm nhà không cần vội", "Tôi lên lịch cho từng góc nhỏ thay vì làm tất cả một ngày. Căn nhà gọn dần mà tôi vẫn có thời gian nghỉ.", { intelligence: 3, health: 1 }, "1F4C5"]],
    ["cho-cu", "1F91D", "Món đồ còn tốt tìm chủ mới",
      "Tôi có vài món đồ lâu không dùng nhưng còn tốt. Giữ lại thì chật nhà, bỏ đi thì tiếc; có lẽ chúng chỉ đang chờ người cần hơn.",
      ["Tặng cho người cần", "Đồ cũ tiếp tục có ích", "Tôi kiểm tra đồ và trao lại cho người cần dùng. Góc nhà rộng hơn, còn món đồ có một cuộc sống mới.", { happiness: 4 }, "1F91D"],
      ["Sắp lại để dùng thường xuyên", "Nhớ lại một món đồ hữu ích", "Tôi chọn món còn phù hợp và đặt ở chỗ dễ dùng. Trước khi mua thêm, tôi đã biết mình đang có gì.", { intelligence: 3 }, "1F9EE"]],
    ["loi-nho", "1F4C5", "Một lời nhờ đúng lúc quá tải",
      "Người quen nhờ tôi giúp thêm một việc, trong khi lịch tuần này đã kín. Tôi muốn giúp nhưng cũng biết mình không có thêm một ngày bí mật trong tuần.",
      ["Nói rõ thời gian có thể giúp", "Giúp đỡ trong khả năng", "Tôi nói rõ lịch của mình và đề nghị một phần việc vừa sức. Lời hứa cụ thể khiến cả hai dễ sắp xếp hơn.", { intelligence: 3, happiness: 1 }, "1F91D"],
      ["Từ chối và gợi ý người phù hợp", "Một lời từ chối có trách nhiệm", "Tôi nói thật rằng mình không thể nhận thêm và chỉ một hướng hỗ trợ khác. Tôi giữ lời với những việc đã nhận.", { intelligence: 2, health: 2 }, "1F4C5"]],
  ],
  37: [
    ["chia-se", "1F4D6", "Có người hỏi kinh nghiệm sống",
      "Một người trẻ hơn hỏi tôi cách sắp xếp cuộc sống. Tôi suýt trả lời như chuyên gia rồi nhớ ra sáng nay mình vẫn đi tìm chìa khóa mười phút.",
      ["Kể điều mình từng học được", "Kinh nghiệm đi cùng sự thật", "Tôi chia sẻ vài cách đã hữu ích với mình và cả những điều chưa làm tốt. Cuộc trò chuyện thoải mái vì chẳng ai phải hoàn hảo.", { intelligence: 2, happiness: 2 }, "1F4D6"],
      ["Cùng tìm cách hợp với họ", "Lắng nghe trước khi khuyên", "Tôi hỏi về hoàn cảnh của họ rồi cùng cân nhắc vài lựa chọn. Mỗi người có một nhịp sống khác nhau.", { intelligence: 3, happiness: 1 }, "1F91D"]],
    ["hop-mat", "1F4F8", "Buổi họp mặt sau nhiều lần hẹn",
      "Bạn bè cũ cuối cùng cũng chọn được ngày gặp. Câu chuyện giờ có nhiều thay đổi, nhưng câu ‘nhớ hồi đó không’ vẫn mở đầu rất hiệu quả.",
      ["Đến gặp và nghe chuyện mới", "Bạn cũ, câu chuyện mới", "Tôi lắng nghe những chặng đường khác nhau và kể về mình. Chúng tôi vẫn tìm được nhiều điều để cười cùng nhau.", { happiness: 4 }, "1F4F8"],
      ["Gọi video khi không thể tới", "Giữ liên lạc từ xa", "Tôi báo trước và gọi hỏi thăm vào lúc phù hợp. Không có mặt trực tiếp vẫn có thể dành sự quan tâm.", { happiness: 2, intelligence: 1 }, "1F4F1"]],
    ["di-bo", "1F6B6", "Lối đi quen có một ngã rẽ mới",
      "Trên đường đi bộ quen thuộc, tôi thấy một lối nhỏ dẫn tới góc công viên chưa từng ghé. Hóa ra gần nhà vẫn còn điều để khám phá.",
      ["Đi thử một vòng vừa sức", "Một góc xanh mới", "Tôi khám phá lối đi mới và nghỉ khi cần. Buổi vận động quen thuộc có thêm một điều thú vị.", { health: 3, happiness: 2 }, "1F331"],
      ["Rủ bạn ghé lần sau", "Một cuộc hẹn ngoài trời", "Tôi chụp lại đường đi và hẹn bạn cùng khám phá. Có thêm một lý do để giữ thói quen đi bộ.", { health: 2, happiness: 2 }, "1F4C5"]],
  ],
  38: [
    ["khach", "1F37D", "Khách đến, món ăn chưa xong",
      "Bạn ghé chơi sớm hơn dự tính, còn món chính chưa nấu xong. Tôi nhìn gian bếp rồi quyết định buổi gặp không nhất thiết phải giống chương trình nấu ăn.",
      ["Rủ bạn cùng chuẩn bị", "Bữa ăn cùng làm", "Chúng tôi vừa nấu vừa trò chuyện. Một chút chậm trễ đổi lấy nhiều tiếng cười và một bữa ăn ngon.", { happiness: 4, intelligence: 1 }, "1F373"],
      ["Đổi sang bữa đơn giản", "Tiếp khách theo cách vừa sức", "Tôi chọn món đơn giản hơn và dành thời gian trò chuyện. Bạn đến để gặp tôi, không phải chấm điểm thực đơn.", { happiness: 3 }, "1F37D"]],
    ["chuyen-ngan", "1F4C5", "Một chuyến đi cần ít hành lý hơn",
      "Tôi chuẩn bị chuyến đi ngắn và nhận ra vali chứa đủ đồ cho một tuần. Cái áo ‘biết đâu cần’ đã có tới ba người anh em.",
      ["Chọn đồ theo lịch thực tế", "Hành lý gọn, chuyến đi nhẹ", "Tôi xem lịch trình và chỉ mang đồ cần thiết. Việc di chuyển dễ hơn mà chuyến đi vẫn đủ những thứ quan trọng.", { intelligence: 3, happiness: 1 }, "1F4C5"],
      ["Chọn nơi gần để nghỉ ngơi", "Một chuyến đổi không khí", "Tôi chọn điểm đến gần, bớt vội và có thời gian thư giãn. Nghỉ ngơi không cần phải đi thật xa.", { health: 2, happiness: 3 }, "1F6B6"]],
    ["cong-thuc", "1F4D6", "Cuốn sổ công thức gia đình",
      "Tôi muốn ghi lại những món ăn quen để không phải hỏi lại mỗi lần. Có người bảo cứ nêm theo cảm giác, nhưng cảm giác của tôi vẫn cần giấy hướng dẫn.",
      ["Ghi công thức và câu chuyện", "Món ăn giữ một phần ký ức", "Tôi ghi cách nấu cùng vài câu chuyện về món ăn. Cuốn sổ vừa hữu ích vừa làm tôi thấy gần gũi với người thân.", { intelligence: 2, happiness: 3 }, "1F4D6"],
      ["Nấu và chụp từng bước", "Học bằng một bữa ăn", "Tôi thử nấu, chụp lại các bước và điều chỉnh phần chưa hợp. Lần sau vào bếp đã có một bản hướng dẫn của riêng mình.", { intelligence: 3 }, "1F373"]],
  ],
  39: [
    ["ho-so", "1F4DA", "Giấy tờ không nên chơi trốn tìm",
      "Tôi cần một giấy tờ cũ nhưng phải mở tới ngăn kéo thứ ba mới thấy. Chuyện nhỏ này khiến tôi muốn thôi giao việc ghi nhớ cho trí nhớ.",
      ["Phân loại và ghi chỗ cất", "Hồ sơ tìm được nhanh hơn", "Tôi sắp xếp giấy tờ theo nhóm, ghi nơi cất và lưu bản sao của tài liệu cần thiết. Lần tìm sau sẽ bớt loay hoay.", { intelligence: 3 }, "1F4DA"],
      ["Dọn từng nhóm một", "Một ngăn kéo gọn trước", "Tôi bắt đầu từ nhóm giấy tờ hay dùng nhất. Một việc nhỏ làm xong còn tốt hơn kế hoạch lớn để mãi trong đầu.", { intelligence: 2, happiness: 1 }, "1F9F9"]],
    ["bat-dau", "1F9E9", "Chưa từng thử không có nghĩa là muộn",
      "Tôi thấy một lớp trải nghiệm mình thích, nhưng nghĩ mình có lẽ lớn tuổi hơn nhiều người ở đó. Rồi tôi đọc thấy dòng ‘dành cho người mới bắt đầu’.",
      ["Đăng ký buổi trải nghiệm", "Buổi đầu ở tuổi ba mươi chín", "Tôi đến thử với tâm thế học hỏi. Sự vụng về ban đầu không ngăn tôi vui khi làm được một điều mới.", { intelligence: 2, happiness: 3 }, "1F9E9"],
      ["Thử phiên bản đơn giản ở nhà", "Bắt đầu từ một góc nhỏ", "Tôi chọn cách trải nghiệm vừa sức và dành một buổi thực hành. Sở thích mới không cần bắt đầu bằng kế hoạch thật lớn.", { intelligence: 2, happiness: 2 }, "1F4D6"]],
    ["nhip-song", "1F45F", "Giữ nhịp thay vì chạy đua",
      "Tôi nhìn lịch gần đây và thấy mình hay bỏ qua giờ nghỉ, bữa ăn và vận động. Có vẻ thứ cần nâng cấp lúc này là cách chia thời gian.",
      ["Sắp lại vài thói quen cơ bản", "Một lịch sống dễ theo hơn", "Tôi chọn giờ sinh hoạt phù hợp hơn và bắt đầu bằng những thay đổi nhỏ. Giữ đều đặn quan trọng hơn làm thật nhiều một ngày.", { health: 3, intelligence: 2 }, "1F4C5"],
      ["Hẹn bạn vận động thường xuyên", "Có người cùng giữ nhịp", "Tôi cùng bạn thống nhất lịch vận động vừa sức. Những buổi gặp vừa giúp chúng tôi khỏe hơn vừa có thời gian hỏi thăm.", { health: 3, happiness: 2 }, "1F6B6"]],
  ],

};

export function createAdultEvents(age) {
  return (stories[age] ?? []).map(([key, code, title, text, ...branches]) => ({
    id: `adult-${age}-${key}`, title, text, ...art(code, title),
    choices: branches.map(([label, resultTitle, resultText, effects, resultCode]) => ensureEventOpenMoji({
      label, title: resultTitle, text: resultText, effects: { ...effects },
      confirmText: "Tiếp tục hành trình!", ...art(resultCode, resultTitle),
    })),
  }));
}
