import { ensureEventOpenMoji } from "./event-openmoji.js";

const art = (code, alt) => {
  const image = new URL(`./img/events/openmoji/color/svg/${code}.svg`, import.meta.url).href;
  return { image, imageAlt: alt, imageFallback: image, imageFallbackAlt: alt };
};

// Tuổi 40 và 45 giữ hai sự kiện thường, dành chỗ cho chuỗi đặc biệt sau này.
// Các câu chuyện không yêu cầu nhân vật có việc làm, kết hôn hoặc có con.
const stories = {
  40: [
    ["sinh-nhat", "1F389", "Bốn mươi, nến hơi chật bánh",
      "Đến sinh nhật bốn mươi, bạn tôi hỏi có cần cắm đủ nến không. Tôi nhìn chiếc bánh nhỏ rồi đề nghị chừa chỗ cho kem. Điều tôi muốn nhất là một buổi tối dễ chịu.",
      ["Rủ vài người thân thiết ăn cơm", "Bữa cơm mừng tuổi mới", "Tôi cùng những người thân thiết ăn một bữa giản dị, kể chuyện và chụp ảnh. Bốn mươi bắt đầu bằng tiếng cười chứ không phải một danh sách thành tích.", { happiness: 4 }, "1F373"],
      ["Viết một lá thư cho mình", "Lời nhắn ở tuổi bốn mươi", "Tôi viết điều mình trân trọng và một mong muốn vừa sức cho những năm tới. Có những điều cần tiếp tục, có những điều đã có thể đặt xuống.", { intelligence: 3, happiness: 2 }, "1F4D6"]],
    ["goc-nha", "1F9F9", "Chiếc ngăn kéo lâu rồi chưa mở",
      "Tôi tìm pin trong ngăn kéo và gặp cả chìa khóa cũ, dây sạc lạ cùng một tờ giấy ghi ‘đừng quên’. Tôi đã quên tờ giấy ấy nói về chuyện gì.",
      ["Dọn từng ngăn, giữ đồ cần thiết", "Một góc nhà dễ tìm đồ", "Tôi phân loại đồ, gom thứ còn dùng được và sắp lại ngăn kéo. Lần tới cần pin, có lẽ tôi sẽ không phải khai quật cả quá khứ.", { intelligence: 3, happiness: 1 }, "1F9F9"],
      ["Giữ riêng những món có kỷ niệm", "Chiếc hộp ký ức nhỏ", "Tôi dành một hộp nhỏ cho đồ có ý nghĩa, còn vật dụng thường ngày được đặt ở chỗ dễ lấy. Nhà gọn hơn mà ký ức vẫn có chỗ ở.", { intelligence: 2, happiness: 3 }, "1F4F8"]],
  ],
  41: [
    ["cong-nghe", "1F4BB", "Ứng dụng đổi chỗ tất cả nút bấm",
      "Ứng dụng quen vừa cập nhật. Nút tôi dùng mỗi ngày biến mất khỏi chỗ cũ, như thể nó cũng muốn đổi môi trường sống.",
      ["Đọc hướng dẫn rồi thử lại", "Một thao tác mới đã quen", "Tôi tìm phần hướng dẫn và thử từng bước. Sau một lúc, giao diện mới bớt lạ và tôi biết thêm một cách làm tiện hơn.", { intelligence: 3 }, "1F4BB"],
      ["Nhờ bạn chỉ rồi ghi chú", "Học nhanh nhờ một lời chỉ", "Bạn hướng dẫn tôi cách dùng. Tôi ghi lại thao tác để lần sau tự làm, rồi cảm ơn bằng một câu chuyện vui.", { intelligence: 2, happiness: 2 }, "1F91D"]],
    ["cay-xanh", "1F331", "Chậu cây nghiêng về phía cửa sổ",
      "Chậu cây trên bàn vươn hẳn về phía cửa sổ. Tôi nhận ra mình chăm tưới nước nhưng chưa để ý chỗ đặt cây có đủ sáng hay không.",
      ["Tìm hiểu rồi đổi vị trí cây", "Một góc sáng phù hợp", "Tôi đọc cách chăm loại cây này và chọn vị trí thích hợp. Chăm cây hóa ra cần quan sát nhiều hơn là tưới theo thói quen.", { intelligence: 2, happiness: 2 }, "1F331"],
      ["Hỏi người hàng xóm mê cây", "Chuyện trò bên chậu lá", "Người hàng xóm chỉ tôi vài mẹo và kể về vườn nhỏ của họ. Tôi mang cây sang chỗ mới, có thêm một người để hỏi chuyện cây cối.", { happiness: 3, intelligence: 1 }, "1F91D"]],
    ["nghi-ngoi", "1F4C5", "Một tối không xếp thêm việc",
      "Tôi định lấp khoảng trống cuối ngày bằng vài việc lặt vặt. Nhìn lịch kín cả tuần, tôi chợt muốn giữ lại một buổi tối cho mình.",
      ["Đi dạo rồi nghỉ sớm", "Một tối thảnh thơi", "Tôi đi bộ một vòng vừa sức, về nhà thư giãn và ngủ đúng giờ. Khoảng trống trong lịch hôm nay có ích thật.", { health: 3, happiness: 2 }, "1F6B6"],
      ["Đọc vài trang sách yêu thích", "Buổi tối có tiếng lật trang", "Tôi tắt thông báo không cần thiết và đọc sách. Không phải hoàn thành cả cuốn, chỉ cần có thời gian tận hưởng nó.", { intelligence: 2, happiness: 2 }, "1F4D6"]],
  ],
  42: [
    ["mon-an", "1F373", "Món quen được nấu theo cách mới",
      "Tôi muốn thử một cách nấu khác cho món ăn quen. Công thức trông đơn giản, nhưng gian bếp của tôi chưa từng đồng ý với chữ ‘chỉ mất mười phút’.",
      ["Thử một phần nhỏ trước", "Một công thức vừa tay", "Tôi làm một phần nhỏ, nếm rồi điều chỉnh. Món ăn chưa hoàn hảo nhưng đủ ngon để lần sau tiếp tục thử.", { intelligence: 2, happiness: 2 }, "1F373"],
      ["Rủ bạn cùng nấu và góp ý", "Hai người, một gian bếp", "Chúng tôi chia việc, cùng nếm và ghi lại cách nấu phù hợp. Bữa ăn có thêm tiếng cười và một công thức mới.", { happiness: 4 }, "1F91D"]],
    ["ho-so", "1F4DA", "Tập giấy tờ dày hơn tôi nhớ",
      "Tôi cần tìm một giấy tờ cũ trong tập hồ sơ. Những tờ quan trọng và tờ hướng dẫn mua nồi cơm đang chung sống rất hòa thuận.",
      ["Phân loại và ghi nhãn từng mục", "Hồ sơ dễ tra cứu", "Tôi tách giấy tờ theo nhóm và ghi nhãn rõ ràng. Việc tìm kiếm lần sau sẽ bớt phụ thuộc vào trí nhớ.", { intelligence: 3 }, "1F4DA"],
      ["Lập danh sách nơi cất bản gốc", "Một bản chỉ đường cho giấy tờ", "Tôi ghi nơi lưu từng bản gốc, tạo bản sao cần thiết và giữ thông tin riêng tư cẩn thận. Tập hồ sơ đã dễ dùng hơn.", { intelligence: 2, happiness: 1 }, "1F4D6"]],
    ["ban-be", "1F4C5", "Cuộc hẹn cứ dời từ tháng này sang tháng khác",
      "Tôi và một người bạn liên tục nhắn ‘hôm nào gặp’. Hôm nào ấy đã đi qua mấy trang lịch mà chưa ghé tới.",
      ["Chốt một buổi gặp ngắn", "Cuối cùng cũng ngồi lại", "Chúng tôi chọn một giờ cụ thể và gặp nhau một lúc. Không cần cả ngày rảnh mới có thể hỏi thăm một người bạn.", { happiness: 4 }, "1F91D"],
      ["Gọi điện ngay khi cả hai rảnh", "Cuộc chuyện trò bù cuộc hẹn", "Tôi gọi bạn và nghe những chuyện mới. Cuộc gặp trực tiếp vẫn để sau, nhưng lời hỏi thăm đã đến được hôm nay.", { happiness: 3 }, "1F4F1"]],
  ],
  43: [
    ["so-thich", "1F3A8", "Buổi vẽ không cần đẹp ngay",
      "Một lớp trải nghiệm vẽ mở gần nhà. Tôi từng thích vẽ nhưng lâu rồi chỉ cầm bút để ghi danh sách mua đồ.",
      ["Đăng ký buổi trải nghiệm", "Bức tranh đầu tiên sau nhiều năm", "Tôi thử phối màu và chấp nhận bức tranh còn vụng. Điều thú vị là được tập trung làm một thứ mình thích.", { happiness: 3, intelligence: 2 }, "1F3A8"],
      ["Tập phác vài nét ở nhà", "Cuốn sổ có thêm hình vẽ", "Tôi dùng giấy bút sẵn có, vẽ chiếc cốc trên bàn. Một sở thích cũ trở lại bằng những nét rất đơn giản.", { intelligence: 2, happiness: 2 }, "1F4D6"]],
    ["san-chung", "1F9F9", "Buổi dọn sân của khu phố",
      "Khu phố tổ chức dọn sân chung vào cuối tuần. Tôi bước xuống thì thấy mọi người đã chia nhau chổi, túi rác và cả chuyện để kể.",
      ["Góp sức dọn một khu vực", "Sân sạch, hàng xóm gần hơn", "Tôi nhận phần việc vừa sức và cùng mọi người dọn sân. Kết thúc buổi, chúng tôi đứng ngắm chỗ ngồi chung sạch sẽ hơn.", { health: 2, happiness: 3 }, "1F9F9"],
      ["Giúp phân loại và gom dụng cụ", "Một việc nhỏ có ích", "Tôi hỗ trợ sắp dụng cụ, phân loại đồ bỏ đi và trả đồ về đúng chỗ. Mỗi người làm một phần, buổi dọn sân nhẹ hơn.", { intelligence: 2, happiness: 2 }, "1F91D"]],
    ["di-bo", "1F6B6", "Bạn đi bộ nhanh hơn tôi tưởng",
      "Tôi hẹn bạn đi bộ và nhận ra hai người có tốc độ khác nhau. Bạn gọi đó là đi thong thả, còn tôi đã bắt đầu đếm ghế nghỉ.",
      ["Nói rõ để cùng giảm nhịp", "Đi cùng nhau theo nhịp vừa sức", "Chúng tôi đi chậm lại và chọn quãng đường phù hợp. Buổi gặp vui hơn khi cả hai đều có thể trò chuyện thoải mái.", { health: 3, happiness: 2 }, "1F6B6"],
      ["Chọn vòng ngắn rồi nghỉ cùng bạn", "Vận động có chỗ nghỉ", "Tôi đề nghị đi một vòng ngắn và ngồi nghỉ. Giữ thói quen vận động dễ hơn khi biết lắng nghe sức mình.", { health: 2, intelligence: 2 }, "1F4C5"]],
  ],
  44: [
    ["anh-cu", "1F4F8", "Một tấm ảnh thiếu tên người chụp",
      "Tôi tìm thấy ảnh một chuyến đi cũ nhưng không nhớ ai chụp. Trong ảnh, cả nhóm còn trẻ và mái tóc của tôi rất tự tin.",
      ["Gửi ảnh hỏi những người bạn cũ", "Ảnh cũ nối lại câu chuyện", "Mọi người nhận ra địa điểm và bổ sung những chuyện tôi đã quên. Một tấm ảnh mở đầu cả buổi hỏi thăm.", { happiness: 4 }, "1F4F8"],
      ["Ghi lại điều mình còn nhớ", "Kỷ niệm có thêm chú thích", "Tôi ghi tên người, địa điểm và những chi tiết chắc chắn nhớ được. Album bớt những tấm ảnh không có câu chuyện.", { intelligence: 2, happiness: 2 }, "1F4D6"]],
    ["chi-tieu", "1F9EE", "Những khoản nhỏ nối thành một hàng dài",
      "Tôi xem lại chi tiêu và phát hiện nhiều khoản đăng ký ít dùng. Mỗi khoản đều nhỏ, nhưng chúng gặp nhau rất đều vào cuối tháng.",
      ["Hủy những dịch vụ không còn cần", "Một danh sách gọn hơn", "Tôi rà lại nhu cầu và hủy các gói không sử dụng. Những khoản sắp tới được ghi rõ để tôi dễ theo dõi.", { intelligence: 3 }, "1F9EE"],
      ["Đặt ngày xem lại ngân sách", "Một thói quen kiểm tra chi tiêu", "Tôi chia khoản cần thiết và khoản có thể giảm, rồi hẹn lịch xem lại hàng tháng. Quản lý tiền bớt mơ hồ khi có con số cụ thể.", { intelligence: 2, happiness: 1 }, "1F4C5"]],
    ["sua-do", "1F9E9", "Chiếc ghế hơi lung lay",
      "Chiếc ghế quen bắt đầu kêu khi tôi ngồi xuống. Tôi kiểm tra và thấy một mối nối lỏng; có lẽ nó đã nhắc tôi từ tuần trước.",
      ["Nhờ người biết sửa kiểm tra", "Chiếc ghế lại chắc chắn", "Tôi nhờ người có kinh nghiệm sửa mối nối và kiểm tra lại ghế. Một món đồ quen được tiếp tục sử dụng an toàn.", { intelligence: 2, happiness: 2 }, "1F91D"],
      ["Tạm cất ghế, dùng chiếc khác", "Đổi chỗ ngồi trước khi sửa", "Tôi đánh dấu ghế cần sửa và dùng chiếc khác. Đồ hỏng có thể chờ xử lý, còn chỗ ngồi nên chắc chắn ngay hôm nay.", { intelligence: 3 }, "1F9E9"]],
  ],
  45: [
    ["sinh-nhat", "1F389", "Bốn mươi lăm, một điều vẫn muốn thử",
      "Sinh nhật bốn mươi lăm, tôi nhìn danh sách những điều từng muốn làm. Có việc đã xong, có việc vẫn chờ một ngày đủ rảnh.",
      ["Chọn một điều nhỏ để bắt đầu", "Mong muốn có ngày hẹn", "Tôi chọn việc phù hợp với thời gian và khả năng hiện tại, rồi đặt lịch bước đầu tiên. Danh sách lần này có thêm hành động.", { intelligence: 3, happiness: 2 }, "1F4C5"],
      ["Ăn mừng những điều đã làm được", "Một buổi tối biết ơn", "Tôi dành thời gian nhớ lại những việc mình đã vượt qua và trò chuyện với người thân thiết. Không chỉ việc chưa làm mới đáng được nhắc tới.", { happiness: 4 }, "1F373"]],
    ["cho-cu", "1F6B6", "Dãy hàng quen đã thay biển hiệu",
      "Tôi ghé khu chợ từng đi nhiều năm trước. Có quầy đã đổi chủ, có quầy vẫn giữ tiếng chào quen thuộc. Con đường cũ mang theo nhiều chuyện mới.",
      ["Dạo một vòng và hỏi thăm", "Một buổi gặp lại nơi quen", "Tôi trò chuyện với người bán quen và nghe chuyện khu phố đổi thay. Chuyến đi ngắn lại cho tôi nhiều điều để nhớ.", { happiness: 3, health: 1 }, "1F91D"],
      ["Chọn nguyên liệu nấu món ngày xưa", "Món ăn gợi một thời", "Tôi mua nguyên liệu trong khoản đã dự tính và nấu lại món quen. Mùi trong bếp khiến một buổi tối bình thường trở nên đặc biệt.", { happiness: 3, intelligence: 1 }, "1F373"]],
  ],
  46: [
    ["huong-dan", "1F4BB", "Người quen cần học cách sao lưu ảnh",
      "Một người quen lo mất ảnh trong điện thoại và hỏi tôi cách sao lưu. Tôi cũng từng có cả album mang tên ‘ảnh cuối cùng, bản cuối thật’.",
      ["Cùng làm từng bước trên máy của họ", "Người quen tự sao lưu được", "Tôi hướng dẫn chậm rãi để họ tự thao tác và kiểm tra ảnh đã lưu. Cả hai nhẹ nhõm khi kỷ niệm được giữ cẩn thận.", { intelligence: 2, happiness: 3 }, "1F4BB"],
      ["Viết hướng dẫn ngắn, dễ xem lại", "Một tờ hướng dẫn hữu ích", "Tôi ghi các bước bằng lời đơn giản và nhắc họ kiểm tra định kỳ. Giúp một người học được cách làm còn hữu ích hơn làm hộ một lần.", { intelligence: 3, happiness: 1 }, "1F4D6"]],
    ["doc-sach", "1F4DA", "Cuốn sách đọc lại thấy khác",
      "Tôi mở cuốn sách từng đọc hồi trẻ. Những trang trước đây lướt qua giờ lại khiến tôi dừng lâu hơn, như thể cuốn sách vừa được viết thêm.",
      ["Đọc chậm và ghi vài suy nghĩ", "Trang cũ, cách nhìn mới", "Tôi ghi những điều mình hiểu khác trước. Cuốn sách vẫn thế, nhưng kinh nghiệm sống đã làm cuộc đọc thay đổi.", { intelligence: 3, happiness: 1 }, "1F4D6"],
      ["Rủ bạn trao đổi đoạn yêu thích", "Một cuộc chuyện trò từ trang sách", "Chúng tôi chọn đoạn mỗi người nhớ nhất và nói về cách hiểu của mình. Tôi nghe thêm những góc nhìn thú vị.", { intelligence: 2, happiness: 2 }, "1F91D"]],
    ["bua-trua", "1F373", "Bữa trưa không nhìn màn hình",
      "Tôi ăn trưa mà vẫn lướt điện thoại. Đến lúc đặt máy xuống, tôi nhận ra đã ăn gần hết mà chưa nhớ món hôm nay có vị gì.",
      ["Cất máy, ăn chậm phần còn lại", "Bữa ăn được chú ý hơn", "Tôi dành thời gian cho bữa ăn và một chút nghỉ ngơi. Khoảng nghỉ giữa ngày dễ chịu hơn khi không thêm thông báo.", { health: 2, happiness: 2 }, "1F373"],
      ["Hẹn một bữa ăn trò chuyện", "Bàn ăn có câu chuyện", "Tôi rủ người quen ăn cùng vào hôm khác và thống nhất cất điện thoại. Bữa trưa thành dịp hỏi thăm thay vì lướt màn hình.", { happiness: 3, health: 1 }, "1F91D"]],
  ],
  47: [
    ["chuyen-gan", "1F4C5", "Chuyến đi có nhiều khoảng nghỉ",
      "Tôi lên lịch một chuyến đi ngắn. Lịch cũ có sáu điểm trong một ngày, còn mong muốn hiện tại của tôi là ngồi ngắm cảnh mà không xem giờ liên tục.",
      ["Bớt điểm đến, giữ thời gian nghỉ", "Một chuyến đi thong thả", "Tôi chọn vài nơi thật muốn ghé và chừa khoảng nghỉ. Chuyến đi bớt vội, những cảnh đã thấy cũng được nhớ rõ hơn.", { health: 2, happiness: 3 }, "1F6B6"],
      ["Chọn một nơi gần để khám phá", "Một ngày đổi không khí", "Tôi tìm một nơi gần trong ngân sách đã dành và đi theo nhịp thoải mái. Không cần đi xa mới có chuyện mới để kể.", { happiness: 3, intelligence: 1 }, "1F4F8"]],
    ["cho-do", "1F9F9", "Món đồ còn tốt nhưng tôi ít dùng",
      "Khi dọn nhà, tôi thấy vài món đồ còn tốt mà nhiều năm chưa dùng. Chúng chiếm chỗ rất chăm chỉ, dù công việc chính đã nghỉ từ lâu.",
      ["Hỏi người quen có ai cần", "Món đồ tìm được người dùng", "Tôi kiểm tra tình trạng đồ rồi tặng cho người cần. Một góc nhà trống hơn và món đồ lại có ích.", { happiness: 3, intelligence: 1 }, "1F91D"],
      ["Gửi đến điểm tiếp nhận đồ cũ", "Dọn nhà và sẻ chia", "Tôi hỏi trước nơi tiếp nhận, làm sạch và gửi những món phù hợp. Việc dọn nhà mang lại niềm vui ngoài căn phòng của mình.", { happiness: 4 }, "1F9F9"]],
    ["nhac-cu", "1F4F1", "Bài hát cũ bất ngờ được phát",
      "Một bài hát quen vang lên lúc tôi đang làm việc nhà. Tôi nhớ giai điệu rất rõ, còn lời thì tự tin hát sai một đoạn.",
      ["Nghe trọn bài rồi tìm lại lời", "Bài hát trở về đúng lời", "Tôi nghỉ vài phút, nghe hết bài và tìm lại lời đã quên. Một kỷ niệm nhỏ làm ngày hôm nay vui hơn.", { happiness: 3, intelligence: 1 }, "1F4F1"],
      ["Gửi bài hát cho bạn cũ", "Một giai điệu nối hai người", "Bạn trả lời bằng một câu chuyện hồi trước. Chúng tôi nhắc lại những ngày cũ rồi hỏi thăm cuộc sống hiện tại.", { happiness: 4 }, "1F91D"]],
  ],
  48: [
    ["ngu-som", "1F4C5", "Đêm nào cũng thêm một tập nữa",
      "Tôi định xem một tập phim rồi ngủ. Mấy tối liền, câu ‘một tập nữa thôi’ đều có phần tiếp theo của nó.",
      ["Đặt giờ dừng xem rõ ràng", "Buổi tối có điểm kết thúc", "Tôi chọn giờ tắt màn hình và giữ lại các tập còn lại cho hôm sau. Sáng hôm sau, tôi có một khởi đầu bớt ngái ngủ.", { health: 3, intelligence: 1 }, "1F4C5"],
      ["Đổi sang đọc vài trang trước khi ngủ", "Một cách nghỉ tối yên hơn", "Tôi đặt điện thoại ra xa và đọc một ít. Buổi tối chậm lại, đủ thời gian nghỉ trước ngày mới.", { health: 2, happiness: 2 }, "1F4D6"]],
    ["nhat-ky", "1F4D6", "Viết lại một chuyện nhỏ trong ngày",
      "Tôi muốn ghi nhật ký nhưng trang đầu làm tôi nghĩ phải có chuyện thật lớn. Hôm nay chỉ có một lời chào dễ mến và bữa ăn vừa miệng.",
      ["Ghi những điều bình thường ấy", "Một trang nhật ký vừa đủ", "Tôi viết vài dòng về lời chào và bữa ăn. Những ngày bình thường cũng có chi tiết đáng giữ lại.", { intelligence: 2, happiness: 2 }, "1F4D6"],
      ["Chụp một ảnh và viết chú thích", "Tấm ảnh có câu chuyện hôm nay", "Tôi chụp góc nhỏ mình thích và thêm một câu chú thích. Ký ức có thể bắt đầu từ một cách ghi rất đơn giản.", { happiness: 3, intelligence: 1 }, "1F4F8"]],
    ["tro-choi", "1F9E9", "Buổi chơi cờ với người hàng xóm",
      "Người hàng xóm rủ tôi chơi một trò trên bàn. Luật không dài, nhưng tôi nghe xong vẫn cần hỏi lại xem lượt của mình được làm gì.",
      ["Chơi thử, hỏi luật khi cần", "Ván đầu có nhiều tiếng cười", "Tôi học qua một ván thử và dần hiểu cách chơi. Thua một ván chẳng ngăn buổi gặp trở nên vui vẻ.", { intelligence: 3, happiness: 2 }, "1F9E9"],
      ["Rủ thêm người cùng chơi", "Chiếc bàn thành cuộc hẹn", "Chúng tôi mời thêm người quen và hướng dẫn nhau. Trò chơi tạo ra một dịp gặp gỡ đơn giản mà vui.", { happiness: 4 }, "1F91D"]],
  ],
  49: [
    ["nhin-lai", "1F4F8", "Những năm bốn mươi trong một album",
      "Tôi nhìn lại ảnh của gần mười năm qua. Có việc từng làm tôi lo rất nhiều giờ đã thành chuyện cũ, còn vài cuộc gặp nhỏ vẫn khiến tôi mỉm cười.",
      ["Chọn ảnh và ghi điều đã học", "Một album có thêm suy nghĩ", "Tôi chọn những khoảnh khắc đáng nhớ và ghi điều chúng dạy mình. Chặng đường đã qua có cả bài học lẫn niềm vui.", { intelligence: 3, happiness: 2 }, "1F4D6"],
      ["Gửi lời cảm ơn một người đã giúp", "Một lời cảm ơn đến đúng người", "Tôi nhắn lời cảm ơn cụ thể cho người từng giúp mình. Họ vẫn nhớ câu chuyện, và cuộc trò chuyện khiến cả hai vui.", { happiness: 4 }, "1F91D"]],
    ["hoc-moi", "1F4BB", "Một kỹ năng chưa có trong danh sách",
      "Tôi thấy một bài hướng dẫn làm điều mình chưa từng thử. Bốn mươi chín tuổi vẫn có buổi đầu tiên, chỉ khác là tôi biết nên bắt đầu vừa sức.",
      ["Thực hành một bài ngắn", "Buổi đầu học một kỹ năng mới", "Tôi làm theo từng bước và thử lại phần chưa hiểu. Hoàn thành một bài nhỏ khiến tôi muốn tiếp tục.", { intelligence: 3, happiness: 1 }, "1F4BB"],
      ["Tìm bạn cùng học hàng tuần", "Một cuộc hẹn để học", "Tôi rủ người quen chia sẻ tiến độ mỗi tuần. Có người cùng trao đổi giúp việc học vui và dễ duy trì hơn.", { intelligence: 2, happiness: 2 }, "1F4C5"]],
    ["hen-tuoi-moi", "1F331", "Một kế hoạch cho tuổi năm mươi",
      "Tuổi năm mươi còn một năm nữa. Tôi nghĩ về cách mình muốn sống mỗi ngày, rồi nhận ra kế hoạch tốt cần chỗ cho nghỉ ngơi và những người mình quý.",
      ["Chọn ba thói quen muốn giữ", "Một kế hoạch có thể thực hiện", "Tôi ghi ba thói quen phù hợp và bắt đầu từ hôm nay. Chặng mới không cần chờ đến đúng sinh nhật mới chuẩn bị.", { health: 2, intelligence: 3 }, "1F4C5"],
      ["Hẹn vài buổi gặp trong năm tới", "Lịch có chỗ cho người thân thiết", "Tôi dành thời gian cho những cuộc gặp mình thường để muộn. Một kế hoạch tốt cũng có thể là biết giữ liên lạc.", { happiness: 3, intelligence: 1 }, "1F91D"]],
  ],
};

export function createMidlifeEvents(age) {
  return (stories[age] ?? []).map(([key, code, title, text, ...branches]) => ({
    id: `midlife-${age}-${key}`, title, text, ...art(code, title),
    choices: branches.map(([label, resultTitle, resultText, effects, resultCode]) => ensureEventOpenMoji({
      label, title: resultTitle, text: resultText, effects: { ...effects },
      confirmText: "Tiếp tục hành trình!", ...art(resultCode, resultTitle),
    })),
  }));
}
