// Bộ Tarot 78 lá, chỉ dùng hướng xuôi. Mỗi lá: ý nghĩa chung (bộ sưu tập), gợi ý ngắn
// cho nhật ký và 4 lời giải theo chủ đề: tình duyên, sự nghiệp, tài chính, cuộc sống.
// Lời giải mang tính gợi mở, không khẳng định chắc chắn chuyện tương lai.

export const tarotTopics = [
  { id: "love", icon: "💘", name: "Tình duyên" },
  { id: "career", icon: "💼", name: "Sự nghiệp" },
  { id: "money", icon: "💰", name: "Tài chính" },
  { id: "life", icon: "🌈", name: "Cuộc sống" },
];

export const tarotGroups = [
  { id: "major", name: "Ẩn chính", icon: "🌟" },
  { id: "wands", name: "Gậy", icon: "🔥" },
  { id: "cups", name: "Cốc", icon: "💧" },
  { id: "swords", name: "Kiếm", icon: "🌬️" },
  { id: "pentacles", name: "Tiền", icon: "🌿" },
];

// [tên, biểu tượng, hiệu ứng, ý nghĩa chung, gợi ý nhật ký, tình duyên, sự nghiệp, tài chính, cuộc sống]
const major = [
  ["Kẻ Khờ", "🎒", { happiness: 2 }, "Khởi đầu mới, tinh thần phiêu lưu và sự hồn nhiên dám thử.", "mạnh dạn bắt đầu điều mới",
    "Đôi khi tình cảm đẹp bắt đầu từ một lời chào giản dị. Cứ mở lòng, đừng quá lo mình chưa hoàn hảo.",
    "Một hướng đi lạ có thể đang chờ. Thử từng bước nhỏ sẽ giúp bạn biết mình có hợp hay không.",
    "Hứng khởi là tốt, nhưng hãy giữ một khoản dự phòng trước khi bước vào cuộc phiêu lưu mới.",
    "Hôm nay hợp để làm điều mình chưa từng làm. Sự tò mò có thể dẫn bạn tới niềm vui bất ngờ."],
  ["Nhà Ảo Thuật", "🪄", { intelligence: 2 }, "Biến ý tưởng thành hành động bằng những gì mình đang có.", "dùng khả năng sẵn có để hành động",
    "Bạn có đủ sự duyên dáng để chủ động. Một lời nói chân thành có thể tạo nên khác biệt.",
    "Kỹ năng của bạn đã sẵn sàng. Hãy cho người khác thấy bạn làm được gì.",
    "Một ý tưởng nhỏ, nếu bắt tay làm ngay, có thể trở thành nguồn thu đáng kể.",
    "Bạn đang cầm trong tay nhiều công cụ hơn mình nghĩ. Thử kết hợp chúng theo cách mới xem."],
  ["Nữ Tư Tế", "🌙", { intelligence: 1, happiness: 1 }, "Trực giác, sự tĩnh lặng và những điều chưa nói thành lời.", "lắng nghe trực giác",
    "Có những cảm xúc không cần vội nói ra. Lắng nghe thêm một chút sẽ giúp bạn hiểu người kia hơn.",
    "Đừng vội quyết định khi chưa đủ thông tin. Quan sát kỹ thường cho bạn câu trả lời.",
    "Trước khi chi tiền, hãy tự hỏi mình có thật sự cần. Cảm giác ngập ngừng đôi khi có lý do.",
    "Một khoảng lặng ngắn mỗi ngày có thể giúp bạn nghe rõ điều mình thực sự muốn."],
  ["Hoàng Hậu", "👑", { appearance: 2 }, "Sự nuôi dưỡng, đủ đầy và chăm sóc bản thân.", "chăm sóc bản thân và người thân",
    "Sự quan tâm ấm áp là ngôn ngữ dễ hiểu nhất. Một bữa cơm hay lời hỏi han cũng đủ làm ai đó vui.",
    "Môi trường làm việc dễ chịu giúp bạn sáng tạo hơn. Hãy chăm chút không gian của mình.",
    "Đầu tư cho sức khỏe và những điều nuôi dưỡng bạn lâu dài thường đáng giá hơn món đồ chóng chán.",
    "Hãy đối xử dịu dàng với chính mình. Nghỉ ngơi đúng lúc cũng là một cách tiến lên."],
  ["Hoàng Đế", "🏛️", { health: 1, intelligence: 1 }, "Trật tự, kỷ luật và sự vững vàng.", "sống có nguyên tắc",
    "Tình cảm bền lâu cần cả sự tin cậy. Giữ lời hứa nhỏ là cách xây nền vững chắc.",
    "Một kế hoạch rõ ràng sẽ giúp bạn dẫn dắt mọi việc tốt hơn sự ngẫu hứng.",
    "Lập ngân sách và bám theo nó. Kỷ luật hôm nay là sự an tâm ngày mai.",
    "Một nếp sinh hoạt đều đặn có thể giúp bạn bớt rối và khỏe hơn."],
  ["Giáo Hoàng", "📜", { intelligence: 2 }, "Truyền thống, học hỏi và lời khuyên từ người đi trước.", "học hỏi từ người đi trước",
    "Lời khuyên của người thân có thể giúp bạn nhìn mối quan hệ rõ hơn. Nghe rồi tự quyết.",
    "Tìm một người hướng dẫn có kinh nghiệm. Học đúng cách giúp bạn đi nhanh mà chắc.",
    "Những cách quản lý tiền truyền thống như tiết kiệm đều đặn vẫn rất đáng tin.",
    "Có những giá trị cũ vẫn còn ý nghĩa. Hãy giữ lại điều tốt và học thêm điều mới."],
  ["Tình Nhân", "💞", { happiness: 2 }, "Sự lựa chọn từ trái tim và những kết nối chân thành.", "chọn điều phù hợp với giá trị của mình",
    "Một kết nối chân thành cần cả hai cùng lựa chọn nhau. Hãy hỏi lòng mình thật sự mong gì.",
    "Bạn có thể đứng trước hai hướng đi. Chọn điều hợp với giá trị của bạn, không chỉ điều dễ hơn.",
    "Khi chi tiêu chung với người khác, nói rõ mong muốn từ đầu sẽ tránh hiểu lầm.",
    "Lựa chọn hôm nay phản ánh con người bạn. Hãy chọn điều khiến bạn thấy thanh thản."],
  ["Cỗ Xe", "🛞", { health: 2 }, "Ý chí, quyết tâm và khả năng giữ hướng đi.", "giữ vững hướng đi",
    "Đừng để những lời bàn tán làm chệch mối quan hệ. Hai người cùng hướng thì sẽ vượt qua.",
    "Giữ tập trung vào mục tiêu chính. Sự bền bỉ có thể đưa bạn vượt qua đối thủ.",
    "Đặt một mục tiêu tiết kiệm cụ thể và theo đuổi nó như một cuộc đua đường dài.",
    "Bạn có đủ năng lượng để tiến lên. Chỉ cần nắm chắc tay lái và biết mình muốn đi đâu."],
  ["Sức Mạnh", "🦁", { health: 2 }, "Lòng can đảm dịu dàng và sự kiên nhẫn.", "mạnh mẽ bằng sự kiên nhẫn",
    "Sự kiên nhẫn và thấu hiểu có sức mạnh hơn tranh cãi. Một lời nói nhẹ nhàng có thể xoa dịu nhiều điều.",
    "Bạn đủ bản lĩnh để xử lý tình huống khó mà không cần nóng vội.",
    "Kiềm chế mong muốn mua sắm bốc đồng cũng là một kiểu sức mạnh.",
    "Đối xử tốt với những lo lắng của mình. Bạn mạnh mẽ hơn bạn nghĩ."],
  ["Ẩn Sĩ", "🏮", { intelligence: 2 }, "Tự suy ngẫm và tìm câu trả lời bên trong.", "dành thời gian suy ngẫm",
    "Một chút thời gian riêng giúp bạn hiểu mình cần gì trong tình cảm.",
    "Lùi lại một bước để nhìn toàn cảnh. Đôi khi câu trả lời đến khi bạn yên tĩnh.",
    "Xem lại các khoản chi trong im lặng có thể cho bạn nhiều phát hiện thú vị.",
    "Một buổi đi dạo một mình, một cuốn sách hay… có thể là món quà bạn cần."],
  ["Bánh Xe Số Phận", "🎡", { happiness: 1, intelligence: 1 }, "Chu kỳ thay đổi và những bước ngoặt.", "đón nhận thay đổi",
    "Mọi mối quan hệ đều có lúc lên xuống. Điều quan trọng là cách hai người cùng đi qua.",
    "Hoàn cảnh có thể thay đổi nhanh. Linh hoạt sẽ giúp bạn nắm bắt cơ hội.",
    "Thu nhập có lúc nhiều lúc ít. Một khoản dự phòng giúp bạn bình tĩnh trước biến động.",
    "Điều không như ý hôm nay có thể mở ra hướng khác ngày mai. Cứ tiếp tục bước."],
  ["Công Lý", "⚖️", { intelligence: 1, happiness: 1 }, "Công bằng, trung thực và trách nhiệm với lựa chọn.", "sống công bằng và trung thực",
    "Sự thẳng thắn và công bằng giúp mối quan hệ lành mạnh. Nói thật, dù khó.",
    "Làm đúng quy trình và minh bạch sẽ giúp bạn được tin tưởng.",
    "Xem kỹ giấy tờ, hợp đồng trước khi ký. Rõ ràng hôm nay tránh rắc rối sau.",
    "Mỗi lựa chọn đều có hệ quả. Hãy chọn điều bạn sẵn sàng chịu trách nhiệm."],
  ["Người Treo Ngược", "🙃", { intelligence: 1 }, "Nhìn mọi việc từ góc độ khác và chấp nhận tạm dừng.", "thử nhìn vấn đề từ góc khác",
    "Thử đặt mình vào vị trí người kia. Có thể bạn sẽ hiểu ra điều trước giờ bỏ lỡ.",
    "Khi mọi việc chững lại, đó là lúc để học thêm và chuẩn bị.",
    "Chưa vội đầu tư. Chờ thêm một chút để nhìn rõ hơn không phải là thua thiệt.",
    "Tạm dừng không có nghĩa là bỏ cuộc. Đôi khi chậm lại để đi xa hơn."],
  ["Cái Chết", "🦋", { happiness: 1 }, "Kết thúc một giai đoạn để mở ra giai đoạn mới. Không mang nghĩa đen.", "khép lại điều cũ để đón điều mới",
    "Buông bỏ những thói quen cũ không còn hợp có thể giúp tình cảm mới mẻ hơn.",
    "Một giai đoạn công việc có thể khép lại, nhường chỗ cho điều phù hợp hơn.",
    "Cắt bớt những khoản chi không còn cần thiết giúp bạn bắt đầu lại nhẹ nhàng.",
    "Giống như con sâu hóa bướm, thay đổi đôi khi khó chịu nhưng mở ra điều đẹp hơn."],
  ["Tiết Chế", "🏺", { health: 2 }, "Cân bằng, điều độ và kiên nhẫn hòa hợp.", "giữ sự cân bằng",
    "Cân bằng giữa cho và nhận giúp mối quan hệ dễ chịu cho cả hai.",
    "Đừng ôm quá nhiều việc. Làm vừa sức giúp bạn đi đường dài.",
    "Chi tiêu điều độ, không quá khắt khe cũng không phung phí.",
    "Ăn ngủ điều độ, làm việc vừa đủ. Sự cân bằng là bí quyết của năng lượng bền."],
  ["Ác Quỷ", "⛓️", { happiness: 1 }, "Nhận ra những ràng buộc, thói quen chưa tốt để tự giải phóng.", "nhận ra thói quen đang trói buộc mình",
    "Hãy để ý những ràng buộc khiến bạn không thoải mái. Tình cảm lành mạnh không làm ai thấy ngột ngạt.",
    "Đừng để áp lực hay thói quen xấu kéo bạn vào vòng lặp mệt mỏi.",
    "Cẩn thận với những khoản chi theo thói quen hoặc lời mời quá hấp dẫn.",
    "Nhận ra điều đang trói buộc mình là bước đầu để thoát ra. Bạn luôn có lựa chọn."],
  ["Tòa Tháp", "🗼", { intelligence: 1 }, "Sự thay đổi bất ngờ giúp lộ ra điều cần sửa. Không đồng nghĩa tai họa.", "bình tĩnh khi mọi thứ thay đổi",
    "Một sự thật bất ngờ có thể làm bạn chao đảo, nhưng cũng giúp hai người hiểu nhau rõ hơn.",
    "Kế hoạch có thể phải điều chỉnh đột ngột. Bình tĩnh xây lại trên nền chắc hơn.",
    "Kiểm tra lại những khoản đầu tư chưa vững. Phát hiện sớm luôn tốt hơn.",
    "Khi điều cũ sụp đổ, bạn có cơ hội xây lại theo cách hợp với mình hơn."],
  ["Ngôi Sao", "⭐", { happiness: 3 }, "Hy vọng, chữa lành và niềm tin vào tương lai.", "giữ hy vọng",
    "Hy vọng là điều đẹp. Cứ chân thành, người hợp với bạn sẽ nhận ra điều đó.",
    "Đừng ngại mơ lớn. Mục tiêu rõ ràng cho bạn động lực mỗi ngày.",
    "Từng khoản tiết kiệm nhỏ như những vì sao, gom lại sẽ thành bầu trời rộng.",
    "Sau những ngày mệt mỏi, hãy tin rằng mọi thứ có thể dần tốt lên."],
  ["Mặt Trăng", "🌕", { intelligence: 1 }, "Những điều mơ hồ, cảm xúc và trí tưởng tượng.", "kiểm chứng trước khi tin",
    "Đừng để suy đoán làm bạn lo lắng. Hỏi thẳng thường tốt hơn tự tưởng tượng.",
    "Thông tin chưa rõ ràng thì đừng vội kết luận. Kiểm chứng trước khi hành động.",
    "Cẩn thận với những lời hứa lợi nhuận mờ ám. Không rõ thì chưa tham gia.",
    "Cảm xúc của bạn đáng được lắng nghe, nhưng đừng để nỗi sợ dẫn đường."],
  ["Mặt Trời", "☀️", { happiness: 3 }, "Niềm vui, sự rõ ràng và năng lượng tích cực.", "lan tỏa niềm vui",
    "Niềm vui giản dị bên nhau là món quà lớn. Cùng làm điều gì đó vui vẻ nhé.",
    "Năng lượng tích cực của bạn có thể truyền cảm hứng cho cả nhóm.",
    "Một ngày tài chính sáng sủa, nhưng vẫn nhớ giữ thói quen tốt.",
    "Hãy ra ngoài, đón nắng và làm điều khiến bạn mỉm cười."],
  ["Phán Xét", "📯", { intelligence: 1, happiness: 1 }, "Thức tỉnh, nhìn lại và chọn cách sống tốt hơn.", "nhìn lại để tiến lên",
    "Nhìn lại những bài học cũ giúp bạn yêu thương trưởng thành hơn.",
    "Đây là lúc đánh giá lại con đường sự nghiệp và lắng nghe tiếng gọi bên trong.",
    "Xem lại các quyết định tài chính đã qua để rút kinh nghiệm cho lần sau.",
    "Mỗi ngày đều có thể là một khởi đầu mới. Tha thứ cho mình và bước tiếp."],
  ["Thế Giới", "🌍", { health: 1, intelligence: 1, happiness: 1, appearance: 1 }, "Hoàn thành một chặng đường và cảm giác trọn vẹn.", "trân trọng những gì đã hoàn thành",
    "Hãy trân trọng hành trình hai người đã cùng nhau đi qua.",
    "Một chặng đường đang dần hoàn thành. Hãy ghi nhận nỗ lực của mình.",
    "Hoàn thành mục tiêu tài chính nhỏ cũng đáng để tự thưởng một chút.",
    "Bạn đã đi một chặng đường dài. Dừng lại một chút để thấy mình đã lớn lên thế nào."],
];

const ranks = ["Át", "Hai", "Ba", "Bốn", "Năm", "Sáu", "Bảy", "Tám", "Chín", "Mười", "Thị Đồng", "Hiệp Sĩ", "Hoàng Hậu", "Vua"];

// Mỗi chất: [ý nghĩa chung, gợi ý nhật ký, tình duyên, sự nghiệp, tài chính, cuộc sống] theo 14 lá.
const minor = {
  wands: { name: "Gậy", icon: "🔥", cards: [
    ["Ngọn lửa đam mê và cảm hứng mới.", "nuôi dưỡng một ngọn lửa đam mê",
      "Một tia rung động mới có thể xuất hiện. Cứ để cảm xúc lớn dần tự nhiên.", "Một ý tưởng mới đang chờ bạn bắt tay vào làm.", "Cảm hứng kiếm thêm thu nhập đang đến, hãy ghi lại ý tưởng.", "Hãy thử một sở thích mới để thắp lại năng lượng."],
    ["Lập kế hoạch và nhìn về phía trước.", "lên kế hoạch cho tương lai",
      "Hai người có thể cùng vẽ ra một kế hoạch nhỏ cho tương lai.", "Đây là lúc nghĩ xa hơn: bạn muốn đi đến đâu trong vài năm tới?", "Lập kế hoạch chi tiêu dài hạn giúp bạn tự tin hơn.", "Ngồi xuống và viết ra ba điều bạn muốn làm năm nay."],
    ["Mở rộng tầm nhìn và chờ đợi kết quả.", "kiên nhẫn chờ thành quả",
      "Mối quan hệ cần thời gian để lớn. Cứ vun đắp đều đặn.", "Những gì bạn gieo trước đây có thể sắp cho kết quả.", "Khoản đầu tư dài hạn cần sự kiên nhẫn.", "Nhìn xa hơn một chút, bạn sẽ thấy nhiều cơ hội."],
    ["Niềm vui, ổn định và ăn mừng.", "ăn mừng những điều nhỏ",
      "Một buổi gặp gỡ vui vẻ có thể làm hai người thêm gắn bó.", "Ăn mừng cột mốc nhỏ giúp cả nhóm có thêm động lực.", "Tình hình khá ổn định, hãy tận hưởng nhưng đừng chủ quan.", "Ở bên gia đình, bạn bè là nguồn năng lượng quý."],
    ["Cạnh tranh và bất đồng nhỏ.", "biến tranh luận thành hợp tác",
      "Bất đồng nhỏ là bình thường. Lắng nghe nhau thay vì cố thắng.", "Cạnh tranh có thể giúp bạn tiến bộ nếu giữ tinh thần lành mạnh.", "Đừng chi tiền chỉ để hơn thua với người khác.", "Tranh luận vui vẻ có thể giúp mọi người hiểu nhau hơn."],
    ["Chiến thắng và được ghi nhận.", "tự tin vào thành quả",
      "Sự tự tin của bạn rất cuốn hút. Hãy là chính mình.", "Nỗ lực của bạn có thể sắp được ghi nhận.", "Một khoản thưởng nhỏ có thể đến từ việc làm tốt.", "Hãy tự hào về những gì mình đã làm được."],
    ["Giữ vững quan điểm.", "kiên định với điều mình tin",
      "Bảo vệ điều mình trân trọng, nhưng nhớ giữ sự mềm mỏng.", "Giữ vững lập trường khi bạn có căn cứ rõ ràng.", "Đừng để người khác thúc ép bạn chi tiền vội vàng.", "Đứng vững trước áp lực cho thấy bạn đã trưởng thành."],
    ["Tốc độ và tin tức đến nhanh.", "nắm bắt cơ hội kịp thời",
      "Một tin nhắn bất ngờ có thể làm bạn mỉm cười cả ngày.", "Mọi việc có thể chuyển động nhanh. Hãy chuẩn bị sẵn sàng.", "Cơ hội đến nhanh, nhưng vẫn kiểm tra kỹ trước khi quyết.", "Một chuyến đi ngắn có thể đem lại năng lượng mới."],
    ["Bền bỉ dù mệt mỏi.", "bền bỉ thêm một chút",
      "Có thể bạn hơi mệt vì những lần thất vọng cũ. Cứ cẩn trọng nhưng đừng khép lòng.", "Bạn đã đi gần đích. Kiên trì thêm một chút.", "Giữ chặt khoản dự phòng, nó sẽ giúp bạn qua lúc khó.", "Nghỉ ngơi để lấy sức, rồi bạn sẽ đi tiếp được."],
    ["Gánh nặng và trách nhiệm nhiều.", "biết chia sẻ gánh nặng",
      "Đừng ôm hết mọi lo toan một mình. Chia sẻ để nhẹ lòng hơn.", "Có thể bạn đang ôm quá nhiều việc. Hãy nhờ hỗ trợ.", "Rà lại các khoản nợ hoặc chi phí đang đè nặng.", "Bỏ bớt việc không cần thiết để có thời gian cho mình."],
    ["Tò mò và tin vui mới.", "giữ sự tò mò",
      "Một người vui tươi có thể mang lại cảm giác mới mẻ.", "Học một kỹ năng mới có thể mở ra hướng đi thú vị.", "Một ý tưởng kiếm tiền nhỏ đáng để thử nghiệm.", "Hãy hỏi nhiều hơn, khám phá nhiều hơn."],
    ["Nhiệt huyết và hành động mạnh mẽ.", "hành động nhưng đừng vội vàng",
      "Nhiệt tình là tốt, nhưng hãy để mối quan hệ có thời gian chín.", "Bạn có năng lượng để bứt phá, chỉ cần có kế hoạch đi kèm.", "Đừng vì hứng khởi mà chi tiêu quá tay.", "Một chuyến phiêu lưu nhỏ có thể làm bạn thấy sống động."],
    ["Tự tin, ấm áp và cuốn hút.", "tỏa sáng bằng sự ấm áp",
      "Sự ấm áp và tự tin của bạn dễ khiến người khác mến.", "Bạn có thể truyền cảm hứng cho người xung quanh.", "Quản lý tiền một cách tự tin và chủ động.", "Hãy làm điều khiến bạn thấy tự hào về mình."],
    ["Tầm nhìn và khả năng dẫn dắt.", "dẫn dắt bằng tầm nhìn",
      "Một mối quan hệ cần định hướng chung. Hãy cùng nhau nói về tương lai.", "Đây là lúc bạn có thể dẫn dắt một việc lớn hơn.", "Tư duy dài hạn giúp bạn ra quyết định tài chính sáng suốt.", "Hãy là người truyền lửa cho chính cuộc đời mình."],
  ] },
  cups: { name: "Cốc", icon: "💧", cards: [
    ["Cảm xúc mới và lòng trắc ẩn.", "mở lòng với cảm xúc mới",
      "Một cảm xúc dịu dàng có thể bắt đầu. Cứ để trái tim mở.", "Làm việc bằng cả trái tim giúp bạn có thêm cảm hứng.", "Chi tiêu cho người mình thương là niềm vui, nhưng nhớ vừa sức.", "Hãy cho phép mình cảm nhận trọn vẹn niềm vui hôm nay."],
    ["Kết nối và sự đồng điệu.", "trân trọng sự đồng điệu",
      "Sự đồng điệu giữa hai người là điều quý. Hãy dành thời gian cho nhau.", "Hợp tác với người hiểu bạn có thể mang lại kết quả tốt.", "Cân nhắc kỹ khi góp vốn chung, rõ ràng sẽ giữ tình cảm.", "Một cuộc trò chuyện chân thành có thể làm bạn nhẹ lòng."],
    ["Niềm vui bên bạn bè.", "vui vẻ cùng bạn bè",
      "Gặp gỡ bạn bè có thể mang lại những mối quen biết thú vị.", "Không khí vui vẻ trong nhóm giúp công việc trôi chảy hơn.", "Đi chơi vui là tốt, nhưng nhớ đặt giới hạn chi tiêu.", "Hãy tụ họp với những người khiến bạn cười nhiều nhất."],
    ["Thờ ơ và cần nhìn lại.", "nhìn thấy những điều đang có",
      "Có thể bạn đang bỏ lỡ sự quan tâm ngay bên cạnh.", "Nếu thấy chán, hãy thử tìm điều mới trong công việc cũ.", "Xem lại những gì mình đã có trước khi muốn thêm.", "Thử biết ơn ba điều nhỏ mỗi ngày."],
    ["Tiếc nuối và học cách buông.", "học cách buông tiếc nuối",
      "Đừng mãi nhìn về điều đã mất. Vẫn còn những điều đẹp đang chờ.", "Một thất bại nhỏ không định nghĩa con người bạn.", "Khoản chi đã lỡ thì rút kinh nghiệm, đừng tự trách quá nhiều.", "Buồn một chút cũng được, rồi hãy nhìn về phía trước."],
    ["Kỷ niệm đẹp và sự ngây thơ.", "trân trọng kỷ niệm đẹp",
      "Những kỷ niệm ngọt ngào có thể làm tình cảm thêm ấm áp.", "Nhớ lại lý do ban đầu bạn yêu công việc này.", "Một món quà nhỏ ý nghĩa đôi khi quý hơn món đắt tiền.", "Ghé thăm nơi cũ hay người xưa có thể sưởi ấm lòng bạn."],
    ["Nhiều lựa chọn và mộng tưởng.", "chọn điều thực tế",
      "Đừng để quá nhiều tưởng tượng làm bạn bối rối. Tình cảm thật cần sự thật.", "Nhiều cơ hội cùng lúc, hãy chọn cái thực tế nhất.", "Cẩn thận với những lời hứa làm giàu nhanh.", "Viết ra lựa chọn của mình để nhìn rõ hơn."],
    ["Rời đi để tìm điều ý nghĩa hơn.", "tìm điều ý nghĩa hơn",
      "Đôi khi buông một điều không hợp giúp bạn tìm được điều đúng.", "Có thể bạn muốn tìm một công việc ý nghĩa hơn. Hãy suy nghĩ kỹ.", "Bớt chi cho những thứ không còn mang lại niềm vui.", "Đi tìm điều khiến tâm hồn bạn thấy đủ đầy."],
    ["Mãn nguyện và điều ước nhỏ.", "biết đủ và mãn nguyện",
      "Cảm giác mãn nguyện bên nhau là điều đáng quý.", "Bạn có thể hài lòng với thành quả hiện tại.", "Một ngày tài chính dễ chịu, hãy tận hưởng có chừng mực.", "Hãy tự thưởng cho mình một niềm vui nhỏ."],
    ["Hạnh phúc gia đình.", "vun đắp hạnh phúc gia đình",
      "Sự bình yên trong gia đình là nền tảng cho tình yêu bền lâu.", "Một môi trường làm việc như gia đình giúp bạn gắn bó.", "Lên kế hoạch tài chính cùng gia đình mang lại sự an tâm.", "Dành thời gian cho người thân là điều không bao giờ phí."],
    ["Tin vui cảm xúc và sáng tạo.", "nuôi dưỡng sự sáng tạo",
      "Một lời tỏ bày ngây ngô nhưng chân thành có thể chạm đến trái tim.", "Ý tưởng sáng tạo có thể làm bạn nổi bật.", "Một khoản nhỏ cho sở thích sáng tạo là đáng giá.", "Hãy vẽ, viết hay hát, cho cảm xúc được bay bổng."],
    ["Lãng mạn và lời mời.", "theo đuổi điều lãng mạn một cách chân thành",
      "Một lời mời lãng mạn có thể đến. Hãy chân thành đáp lại.", "Một đề nghị hợp tác có thể xuất hiện, hãy xem kỹ.", "Đừng để cảm xúc dẫn dắt quyết định tài chính.", "Hãy làm một điều lãng mạn cho chính mình."],
    ["Thấu cảm và quan tâm.", "lắng nghe bằng sự thấu cảm",
      "Sự thấu cảm của bạn giúp người kia thấy an toàn.", "Bạn có thể là người hỗ trợ tinh thần cho đồng nghiệp.", "Chi tiêu vì lòng tốt là đẹp, nhưng nhớ chăm lo cho mình nữa.", "Lắng nghe cảm xúc của mình và của người khác."],
    ["Điềm tĩnh trong cảm xúc.", "giữ bình tĩnh trước cảm xúc",
      "Sự điềm tĩnh giúp bạn giải quyết hiểu lầm nhẹ nhàng.", "Bình tĩnh dẫn dắt khi mọi người căng thẳng.", "Quyết định tài chính khi đã bình tĩnh luôn tốt hơn.", "Học cách chấp nhận cảm xúc mà không bị cuốn theo."],
  ] },
  swords: { name: "Kiếm", icon: "🌬️", cards: [
    ["Sự rõ ràng và sự thật.", "nhìn rõ sự thật",
      "Một cuộc nói chuyện rõ ràng có thể giải tỏa khúc mắc.", "Một ý tưởng sắc bén có thể giải quyết vấn đề lâu nay.", "Nhìn thẳng vào con số thật của tài chính.", "Sự thật đôi khi khó nghe nhưng giúp bạn tự do."],
    ["Phân vân và cần quyết định.", "dám đưa ra quyết định",
      "Đừng né tránh cảm xúc. Đối diện giúp bạn biết mình muốn gì.", "Trì hoãn quyết định có thể làm bạn mệt hơn.", "Cân nhắc hai lựa chọn tài chính bằng thông tin thật.", "Thử lắng nghe cả lý trí lẫn trái tim."],
    ["Nỗi buồn và chữa lành.", "cho phép mình chữa lành",
      "Một nỗi buồn có thể ghé qua, nhưng nó sẽ không ở lại mãi.", "Một lời chỉ trích có thể làm bạn chạnh lòng. Rút điều hữu ích rồi bước tiếp.", "Một khoản mất mát nhỏ là bài học, không phải dấu chấm hết.", "Cho phép mình buồn, rồi nhẹ nhàng chữa lành."],
    ["Nghỉ ngơi và hồi phục.", "nghỉ ngơi để hồi phục",
      "Đôi khi cả hai cần không gian riêng để nhớ nhau hơn.", "Nghỉ ngơi một chút giúp bạn làm việc hiệu quả hơn.", "Tạm dừng các quyết định lớn khi bạn đang mệt.", "Ngủ đủ giấc là món quà bạn nên tặng mình."],
    ["Xung đột và cái giá của chiến thắng.", "chọn hòa khí thay vì hơn thua",
      "Thắng một cuộc tranh cãi không quan trọng bằng giữ được nhau.", "Đừng hạ người khác để mình nổi bật.", "Tránh những thương vụ được lợi trước mắt nhưng mất lòng tin.", "Đôi khi lùi một bước là chiến thắng thật sự."],
    ["Chuyển tiếp sang nơi yên bình hơn.", "bước sang giai đoạn yên bình hơn",
      "Mối quan hệ có thể đang đi qua sóng gió để đến nơi bình yên.", "Một thay đổi môi trường làm việc có thể tốt cho bạn.", "Dần ổn định lại tài chính sau giai đoạn khó.", "Một chuyến đi có thể giúp bạn nhẹ lòng."],
    ["Khéo léo và tính toán.", "hành động khéo léo nhưng trung thực",
      "Thẳng thắn vẫn tốt hơn những toan tính trong tình cảm.", "Hãy khéo léo nhưng minh bạch trong công việc.", "Cẩn thận với giấy tờ và những thỏa thuận mập mờ.", "Tìm cách thông minh để giải quyết việc khó."],
    ["Cảm giác bị bó buộc.", "tìm lối ra cho mình",
      "Nếu thấy mình bị bó buộc, hãy nói ra điều bạn cần.", "Áp lực có thể làm bạn nghĩ mình hết lựa chọn, nhưng thực ra vẫn còn.", "Một khoản nợ có vẻ khó, hãy chia nhỏ để giải quyết.", "Bạn có nhiều tự do hơn mình nghĩ. Hãy thử bước ra."],
    ["Lo âu và suy nghĩ quá nhiều.", "bớt lo âu những điều chưa xảy ra",
      "Đừng để suy nghĩ ban đêm vẽ ra những nỗi lo không có thật.", "Chia sẻ áp lực với người tin cậy sẽ giúp bạn nhẹ đi.", "Lo lắng về tiền? Viết ra kế hoạch cụ thể sẽ dễ thở hơn.", "Hít thở sâu. Phần lớn nỗi lo không xảy ra như ta nghĩ."],
    ["Kết thúc một nỗi đau.", "khép lại nỗi đau cũ",
      "Một chuyện buồn cũ có thể khép lại, nhường chỗ cho bình yên.", "Một giai đoạn vất vả đã qua. Bạn có thể bắt đầu lại.", "Khép lại khoản lỗ cũ và bắt đầu kế hoạch mới.", "Điều tệ nhất đã qua. Bình minh sẽ đến."],
    ["Ham học hỏi và quan sát.", "giữ tinh thần ham học",
      "Tìm hiểu nhau qua những câu hỏi chân thành.", "Tinh thần ham học giúp bạn tiến bộ nhanh.", "Tìm hiểu kỹ trước khi đầu tư.", "Đọc một cuốn sách mới có thể mở ra góc nhìn mới."],
    ["Quyết đoán và nhanh nhạy.", "quyết đoán nhưng lắng nghe",
      "Đừng vội vàng nói ra lời có thể làm tổn thương. Nghĩ một nhịp đã.", "Quyết đoán giúp bạn xử lý việc gấp, nhưng nhớ lắng nghe góp ý.", "Hành động nhanh khi đã có thông tin rõ ràng.", "Nhanh nhẹn là tốt, nhưng đừng quên tận hưởng."],
    ["Thẳng thắn và độc lập.", "nói thật một cách tử tế",
      "Sự thẳng thắn tử tế giúp tình cảm bớt hiểu lầm.", "Góc nhìn khách quan của bạn có giá trị với cả nhóm.", "Tự chủ tài chính mang lại cho bạn sự tự do.", "Học cách nói 'không' khi cần."],
    ["Lý trí và công tâm.", "dùng lý trí để quyết định",
      "Hãy dùng cả lý trí để nhìn nhận mối quan hệ.", "Quyết định dựa trên dữ kiện sẽ khiến mọi người tin bạn.", "Phân tích kỹ các con số trước khi chọn.", "Suy nghĩ rõ ràng giúp bạn tháo gỡ nhiều chuyện rối."],
  ] },
  pentacles: { name: "Tiền", icon: "🌿", cards: [
    ["Cơ hội vật chất mới.", "nắm bắt cơ hội thực tế",
      "Một mối quan hệ có thể bắt đầu từ những điều thực tế và ổn định.", "Một cơ hội công việc thực tế có thể xuất hiện.", "Một hạt giống tài chính nhỏ, chăm sóc tốt sẽ lớn dần.", "Bắt đầu một thói quen tốt từ hôm nay."],
    ["Cân bằng nhiều việc.", "linh hoạt cân bằng mọi việc",
      "Cân bằng giữa công việc và tình cảm giúp cả hai đều vui.", "Bạn có thể phải xoay xở nhiều việc. Ưu tiên là chìa khóa.", "Cân đối thu chi linh hoạt khi có nhiều khoản cùng lúc.", "Đừng quên dành thời gian cho chính mình giữa bộn bề."],
    ["Hợp tác và tay nghề.", "làm việc nhóm để tạo giá trị",
      "Cùng nhau xây dựng điều gì đó giúp hai người gắn kết.", "Làm việc nhóm và học hỏi tay nghề mang lại kết quả tốt.", "Hợp tác đúng người có thể giúp tài chính vững hơn.", "Học thêm một kỹ năng thực tế có ích lâu dài."],
    ["Giữ gìn và an toàn.", "giữ gìn nhưng đừng quá khép kín",
      "Đừng giữ chặt quá mức. Tình cảm cần không gian để thở.", "Giữ vững vị trí là tốt, nhưng đừng sợ thử thách mới.", "Tiết kiệm là tốt, nhưng đừng quá khắt khe với mình.", "An toàn là cần, nhưng đôi khi hãy mở lòng hơn."],
    ["Khó khăn tạm thời.", "tìm sự giúp đỡ khi khó khăn",
      "Lúc khó khăn, hãy để người thân đồng hành cùng bạn.", "Giai đoạn khó có thể khiến bạn chùn bước. Hãy tìm sự hỗ trợ.", "Rà soát chi tiêu và tìm hỗ trợ khi cần.", "Bạn không cô đơn. Hãy mở lời nhờ giúp đỡ."],
    ["Cho và nhận.", "cho đi và đón nhận",
      "Sự sẻ chia hai chiều giúp tình cảm cân bằng.", "Một người có thể hỗ trợ bạn, và bạn cũng có thể giúp người khác.", "Cho đi trong khả năng, nhận lại với lòng biết ơn.", "Một hành động tử tế nhỏ có thể làm ai đó vui cả ngày."],
    ["Kiên nhẫn chờ thu hoạch.", "kiên nhẫn chờ thu hoạch",
      "Tình cảm cần thời gian để đơm hoa. Đừng vội.", "Kết quả công việc cần thêm thời gian. Cứ kiên trì.", "Cây tiền tiết kiệm đang lớn từng chút. Đừng vội hái quả khi nó chưa chín.", "Đánh giá lại chặng đường và tiếp tục chăm chút."],
    ["Chăm chỉ rèn kỹ năng.", "kiên trì rèn kỹ năng",
      "Chăm chút từng điều nhỏ cho nhau là cách yêu bền bỉ.", "Bạn đang tiến bộ qua từng lần luyện tập. Làm chưa nhanh cũng được, miễn hôm nay chắc tay hơn hôm qua.", "Thu nhập tăng dần nhờ kỹ năng được mài giũa.", "Tập trung làm tốt một việc mỗi ngày."],
    ["Tự chủ và tận hưởng.", "tận hưởng thành quả tự lập",
      "Bạn đủ đầy khi ở một mình, và điều đó làm bạn cuốn hút hơn.", "Sự độc lập trong công việc là thành quả đáng tự hào.", "Tận hưởng những gì mình làm ra, có chừng mực.", "Dành một buổi chiều thư thả cho chính mình."],
    ["Bền vững và gia đình.", "xây dựng nền tảng lâu dài",
      "Nghĩ về một tương lai ổn định cùng người thân yêu.", "Xây dựng nền tảng lâu dài cho sự nghiệp.", "Kế hoạch tài chính dài hạn cho gia đình là điều đáng làm.", "Trân trọng truyền thống và những người đi trước."],
    ["Chăm học và thực tế.", "học hỏi một cách thực tế",
      "Một người chân thành, thực tế có thể khiến bạn chú ý.", "Một khóa học thực tế có thể giúp bạn tiến xa.", "Học cách quản lý tiền từ những bước cơ bản.", "Đặt mục tiêu nhỏ và hoàn thành từng cái."],
    ["Đều đặn và đáng tin.", "đều đặn từng bước",
      "Sự đáng tin cậy là điều khiến người khác muốn ở lại.", "Làm việc đều đặn, chắc chắn sẽ được ghi nhận.", "Tiết kiệm đều đặn, dù ít, cũng tạo nên khác biệt.", "Chậm mà chắc vẫn là một cách tiến lên."],
    ["Chu đáo và ấm áp.", "chăm lo chu đáo",
      "Sự chu đáo của bạn làm người kia cảm thấy được yêu thương.", "Bạn có thể vừa làm tốt vừa chăm lo cho người khác.", "Quản lý tài chính gia đình khéo léo mang lại bình yên.", "Một ngôi nhà ấm cúng là nơi nạp năng lượng tốt nhất."],
    ["Thành công và vững vàng.", "vững vàng với thành quả",
      "Một tình cảm vững vàng được xây bằng sự ổn định.", "Sự nghiệp vững vàng là kết quả của nhiều năm nỗ lực.", "Tài chính ổn định giúp bạn rộng lượng hơn.", "Hãy dùng những gì mình có để làm điều tốt đẹp."],
  ] },
};

const roman = ["0", "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X", "XI", "XII", "XIII", "XIV", "XV", "XVI", "XVII", "XVIII", "XIX", "XX", "XXI"];

export const tarotCards = [
  ...major.map(([name, icon, effect, meaning, hint, love, career, money, life], index) => ({
    id: `major-${index}`, group: "major", number: roman[index], name, icon, effect, meaning, hint,
    readings: { love, career, money, life },
  })),
  ...Object.entries(minor).flatMap(([suit, data]) => data.cards.map(([meaning, hint, love, career, money, life], index) => ({
    id: `${suit}-${index + 1}`, group: suit, number: ranks[index], name: `${ranks[index]} ${data.name}`, icon: data.icon,
    meaning, hint, readings: { love, career, money, life },
  }))),
];
