"""Compile the editorial, per-scene illustration assignments.

The build refuses uncovered text or ambiguous exact keys. Text changes must
be reviewed instead of silently falling through a keyword classifier.
"""
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
DEST=ROOT/'js/img/events/openmoji'
records=[]
for name in ('young','adult','later'):
    records.extend(json.loads((DEST/f'reviewed-{name}.json').read_text(encoding='utf-8')))

def key(record):
    return (record['sceneTitle'],(record.get('text') or '').strip(),record['slot'])

def signature(record):
    return tuple(record.get(field) for field in ('action','code','prop','mood','recipient'))

reviewed={}
for record in records:
    identity=key(record)
    if identity in reviewed:
        assert signature(reviewed[identity])==signature(record),f'Conflicting review: {identity}'
    reviewed[identity]=record

audit=json.loads((ROOT/'js/img/events/full-media-audit.json').read_text(encoding='utf-8'))
missing=[]
for row in audit:
    identity=(row['title'],(row.get('text') or '').strip(),'scene' if row['slot']=='scene' else 'result')
    if identity not in reviewed: missing.append(dict(age=row['age'],sceneTitle=identity[0],text=identity[1],slot=identity[2]))
if missing:
    (DEST/'unreviewed.json').write_text(json.dumps(missing,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    raise SystemExit(f'{len(missing)} unreviewed slots; see openmoji/unreviewed.json')

# Bind stable choice labels as well as text. This covers generated names,
# salaries and ages without allowing unrelated actions to match a keyword.
bindings={}
for row in audit:
    identity=(row['title'],(row.get('text') or '').strip(),'scene' if row['slot']=='scene' else 'result')
    binding=(row['title'],row.get('label') or '',identity[2])
    bindings.setdefault(binding,[]).append(identity)
safe_bindings=[]
for binding,identities in bindings.items():
    signatures={signature(reviewed[identity]) for identity in identities}
    if len(signatures)==1:
        safe_bindings.append([*binding,list(identities[0])])

result_titles={}
for row in audit:
    title=row.get('resultTitle') or (row['title'] if row['slot']=='result' else None)
    if not title or row['slot'].startswith('transition'):continue
    identity=(row['title'],(row.get('text') or '').strip(),'result')
    if identity in reviewed:result_titles.setdefault(title,[]).append(identity)
safe_result_titles=[]
for title,identities in result_titles.items():
    if len({signature(reviewed[identity]) for identity in identities})==1:
        safe_result_titles.append([title,list(identities[0])])

entries=[]
for identity,record in sorted(reviewed.items()):
    assert record['action'] and record['code'] and record['label'],record
    plan={field:record[field] for field in ('action','code','label','prop','mood','recipient') if record.get(field)}
    entries.append([*identity,plan])
source='// Generated by scripts/build-reviewed-openmoji.py from reviewed scene/result text.\n'
source+='export const openMojiReviewRevision = 3;\n'
source+='export const reviewedOpenMojiEntries = '+json.dumps(entries,ensure_ascii=False,separators=(',',':'))+';\n'
source+='export const reviewedOpenMojiBindings = '+json.dumps(safe_bindings,ensure_ascii=False,separators=(',',':'))+';\n'
source+='export const reviewedResultTitles = '+json.dumps(safe_result_titles,ensure_ascii=False,separators=(',',':'))+';\n'
(ROOT/'js/reviewed-event-openmoji.js').write_text(source,encoding='utf-8')
(DEST/'unreviewed.json').unlink(missing_ok=True)
print(f'Compiled {len(entries)} explicit assignments covering {len(audit)} slots and {len(safe_bindings)} stable bindings.')
