"""Cache the audited GIPHY selection; keep remote fallback for unavailable GIFs."""
import concurrent.futures
import json
from pathlib import Path
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
DEST = ROOT / "js/img/events/gifs"


def download(gif_id):
    target = DEST / f"{gif_id}.gif"
    data = target.read_bytes() if target.exists() else urllib.request.urlopen(
        urllib.request.Request(
            f"https://media.giphy.com/media/{gif_id}/200w.gif",
            headers={"User-Agent": "HoiSinhNewLifeGame-assets/1.0"},
        ), timeout=12,
    ).read()
    if not data.startswith((b"GIF87a", b"GIF89a")):
        raise ValueError("Response is not a GIF")
    if not target.exists():
        target.write_bytes(data)
    return gif_id


if __name__ == "__main__":
    DEST.mkdir(parents=True, exist_ok=True)
    ids = json.loads((ROOT / "js/img/events/gif-download-list.json").read_text(encoding="utf-8"))
    cached, failures = [], []
    with concurrent.futures.ThreadPoolExecutor(max_workers=6) as pool:
        jobs = {pool.submit(download, gif_id): gif_id for gif_id in ids}
        for future in concurrent.futures.as_completed(jobs):
            try:
                cached.append(future.result())
            except Exception as error:
                failures.append(f"{jobs[future]}: {error}")
    (ROOT / "js/cached-event-gifs.js").write_text(
        "// Generated by scripts/cache-event-gifs.py.\nexport const cachedEventGifIds = "
        + json.dumps(sorted(cached)) + ";\n", encoding="utf-8",
    )
    print(f"Cached {len(cached)}/{len(ids)} valid GIFs.")
    for failure in failures:
        print(failure)
